### ISSUE TITLE
Layout with LaTeX labels

### ISSUE THREAD

**Issue by basnijholt** [holoviz/holoviews#128]
``` python
hv.Image(np.random.rand(10,10)).relabel(r"$a$") + hv.Image(np.random.rand(10,10)).relabel(r"$a$")
```

```
Traceback (most recent call last):
  File "/home/bnijholt/python/env_stable/lib/python2.7/site-packages/holoviews/ipython/display_hooks.py", line 215, in wrapped
    **kwargs)
  File "/home/bnijholt/python/env_stable/lib/python2.7/site-packages/holoviews/ipython/display_hooks.py", line 277, in layout_display
    layoutplot = LayoutPlot(layout, **opts(layout, size))
  File "/home/bnijholt/python/env_stable/lib/python2.7/site-packages/holoviews/plotting/plot.py", line 937, in __init__
    raise ValueError("Cannot display empty layout")
ValueError: Cannot display empty layout
Out[346]:
:Layout
```

**Comment by jlstevens** [comment]
Thanks for the report!  

I can reproduce this issue. It looks like group support LaTeX fine but we not sanitizing label properly (or similar!) causing this issue.

**Comment by philippjfr** [comment]
The fix above should have resolved this issue. Please let us know if you still have issues, for now I'll close the issue.

**Comment by bacalfa** [comment]
I'm not getting a LaTeXed label in the following (just an example):

```
xs = range(-10,11)
ys = [100-x**2 for x in xs]
distance = hv.Dimension('distance', label='Horizontal distance', unit='$\times$ g')
height = hv.Dimension(('height','Height above sea level'), unit='m')
curve = hv.Curve((xs, ys), distance, height)
curve
```

![image](https://user-images.githubusercontent.com/1297074/34950169-6314826a-f9e0-11e7-84df-a9ad36fc47cd.png)


bokeh=0.12.13=py36h047fa9f_0
holoviews=1.9.2=py36_0

**Comment by jlstevens** [comment]
@bacalfa I'm afraid LaTeX support is currently for the matplotlib backend only.

HoloViews will support LaTeX in Bokeh plots once Bokeh itself supports it. See issue
https://github.com/bokeh/bokeh/issues/6031.

Perhaps we ought to find a suitable place to mention this in the docs?

**Comment by ChristopherMayes** [comment]
Bokeh supports latex now: https://docs.bokeh.org/en/latest/docs/user_guide/styling.html?highlight=latex#latex

**Comment by ChristopherMayes** [comment]
Shouldn't this issue be reopened @jlstevens or @philippjfr ? The above example still doesn't work (even with ` unit=r'$$\times$$ g'`).
