### ISSUE TITLE
`arrow_color` is broken

### ISSUE THREAD

**Issue by WeirdKeksButtonK** [holoviz/holoviews#4328]
#### ALL software version info
python 3.7.5
bokeh 2.0.0
holoviews 1.13.1
jupyterlab 1.2.4

#### Description of expected behavior and the observed behavior
The following code:
```python
hv.Arrow(0.5, 0.5, 'ABC', 'v').opts(arrow_color='green')
```
leads to the following error:
```
AttributeError [Call holoviews.ipython.show_traceback() for details]
unexpected attribute 'color' to NormalHead, similar attributes are line_color or fill_color
```
It is strange, because the option "arrow_color" is listed in `hv.help(hv.Arrow)`. The problem remains even if `.opts(hv.opts.Arrow(...))`

`hv.ipython.show_traceback()` doesn't tell much:
```
Traceback (most recent call last):

  File "/home/ygorishniy/miniconda3/envs/tab/lib/python3.7/site-packages/holoviews/plotting/bokeh/element.py", line 1501, in _init_glyphs
    renderer, glyph = self._init_glyph(plot, mapping.get(key, {}), properties, key)

  File "/home/ygorishniy/miniconda3/envs/tab/lib/python3.7/site-packages/holoviews/plotting/bokeh/annotation.py", line 335, in _init_glyph
    end = arrow_end(**properties) if arrow_end else None

  File "/home/ygorishniy/miniconda3/envs/tab/lib/python3.7/site-packages/bokeh/model.py", line 234, in __init__
    super().__init__(**kwargs)

  File "/home/ygorishniy/miniconda3/envs/tab/lib/python3.7/site-packages/bokeh/core/has_props.py", line 246, in __init__
    setattr(self, name, value)

  File "/home/ygorishniy/miniconda3/envs/tab/lib/python3.7/site-packages/bokeh/core/has_props.py", line 281, in __setattr__
    (name, self.__class__.__name__, text, nice_join(matches)))

AttributeError: unexpected attribute 'color' to NormalHead, similar attributes are line_color or fill_color
```

**Comment by philippjfr** [comment]
Thanks, we'll fix this asap.
