### ISSUE TITLE
ISSUE: Unable to enable holoviews extension in k8 deployed Jupyter notebook "Future exception was never retrieved"

### ISSUE THREAD

**Issue by tracebackerror** [holoviz/holoviews#4542]
We are trying to use Holoviews in our environment  which is deployed in  k8 clusters. but on enabling the extension it run indefinite time and never completed execution. 

On debugging in logs we found there is an tornado and asyncio  error "asyncio:Future exception was never retrieved", "tornado.websocket.WebSocketClosedError"

#### ALL software version info
tornado==6.0.4
pyzmq==19.0.1
bokeh==2.1.1
holoviews==1.13.3
prompt-toolkit==3.0.5
panel==0.9.7
jupyter==1.0.0
jupyter-client==6.1.5
jupyter-console==6.1.0
jupyter-core==4.6.3
jupyterhub==0.9.4
ipykernel==5.3.1
nbconvert==5.6.1

Python 3.6.2

#### Description of expected behavior and the observed behavior
Expected the holoviews should be loaded in jupyter environment but its not getting loaded.

#### Complete, minimal, self-contained example code that reproduces the issue

```
import holoviews as hv
hv.extension('bokeh')
```

#### Stack traceback and/or browser JavaScript console output
```
ERROR:asyncio:Future exception was never retrieved
future: <Future finished exception=WebSocketClosedError()>
Traceback (most recent call last):
  File "/home/XXXX/pyenv/versions/3.6.2/lib/python3.6/site-packages/tornado/websocket.py", line 874, in wrapper
    yield fut
  File "/home/XXXX/.pyenv/versions/3.6.2/lib/python3.6/site-packages/tornado/gen.py", line 1133, in run
    value = future.result()
tornado.iostream.StreamClosedError: Stream is closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/XXXX/.pyenv/versions/3.6.2/lib/python3.6/site-packages/tornado/gen.py", line 1141, in run
    yielded = self.gen.throw(*exc_info)
  File "/home/XXXX/.pyenv/versions/3.6.2/lib/python3.6/site-packages/tornado/websocket.py", line 876, in wrapper
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
ERROR:asyncio:Future exception was never retrieved
future: <Future finished exception=WebSocketClosedError()>
Traceback (most recent call last):
  File "/home/XXXX/.pyenv/versions/3.6.2/lib/python3.6/site-packages/tornado/websocket.py", line 874, in wrapper
    yield fut
  File "/home/XXXX/.pyenv/versions/3.6.2/lib/python3.6/site-packages/tornado/gen.py", line 1133, in run
    value = future.result()
tornado.iostream.StreamClosedError: Stream is closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/XXXX/.pyenv/versions/3.6.2/lib/python3.6/site-packages/tornado/gen.py", line 1141, in run
    yielded = self.gen.throw(*exc_info)
  File "/home/XXXX/.pyenv/versions/3.6.2/lib/python3.6/site-packages/tornado/websocket.py", line 876, in wrapper
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
ERROR:asyncio:Future exception was never retrieved
future: <Future finished exception=WebSocketClosedError()>
Traceback (most recent call last):
  File "/home/XXXX/.pyenv/versions/3.6.2/lib/python3.6/site-packages/tornado/websocket.py", line 874, in wrapper
    yield fut
  File "/home/XXXX/.pyenv/versions/3.6.2/lib/python3.6/site-packages/tornado/gen.py", line 1133, in run
    value = future.result()
tornado.iostream.StreamClosedError: Stream is closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/XXXX/.pyenv/versions/3.6.2/lib/python3.6/site-packages/tornado/gen.py", line 1141, in run
    yielded = self.gen.throw(*exc_info)
  File "/home/XXXX/.pyenv/versions/3.6.2/lib/python3.6/site-packages/tornado/websocket.py", line 876, in wrapper
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
```

#### Screenshots or screencasts of the bug in action
![image](https://user-images.githubusercontent.com/8272799/89149065-2662f500-d579-11ea-9fe5-23a1a1767b24.png)

**Comment by philippjfr** [comment]
Thanks for the issue. Can you use other libraries that depend on Websockets to work? For example can you use ipywidgets?

**Comment by tracebackerror** [comment]
yes Philip. Ipywidgets is working as expected. But Holoviews  awaits in running state for indefinite time. And in background it throws the above mentioned  errors.

ipywidgets==7.5.1
![image](https://user-images.githubusercontent.com/8272799/89178318-fc2a2b00-d5aa-11ea-9bfa-c438d92cc0ff.png)

**Comment by tracebackerror** [comment]
Do we know why it's causing the Tornado and Asyncio error in the background. Because I'm trying to fix it from past one week. But didn't got any work around.

**Comment by philippjfr** [comment]
Really sorry I never followed up here. Just don't see what the extension has to do with Websockets. Please reopen if this issue persists and we can hopefully dig deeper.
