### ISSUE TITLE
Image with datetime index raises TypeError with matplotlib backend

### ISSUE THREAD

**Issue by FRidh** [holoviz/holoviews#4629]
Thanks for contacting us! Please read and follow these instructions carefully, then delete this introductory text to keep your issue easy to read. Note that the issue tracker is NOT the place for usage questions and technical assistance; post those at [Discourse](https://discourse.holoviz.org) instead. Issues without the required information below may be closed immediately.

#### ALL software version info
(this library, plus any other relevant software, e.g. bokeh, python, notebook, OS, browser, etc)

Python 3.8.5
NixOS 20.09.20200831.707bed5

Versions of packages in my Python environment:
```
[
  "/nix/store/0bv737c8l03r6vm55fgfzcirmqk047j4-python3.8-openpyxl-3.0.5.drv",
  "/nix/store/0kdc4lyrm1b8qadjvacmfwi5aw10f8bg-python3.8-jupyterlab_server-1.2.0.drv",
  "/nix/store/0krwcvwyyw0nbqgv6m7ilkd9nlr379v1-python3.8-nbconvert-5.6.1.drv",
  "/nix/store/12vvql2bfs7i7zpl6a2bfq858bghdgmx-python3.8-et_xmlfile-1.0.1.drv",
  "/nix/store/19bawm6cbq5s41xw7spgznf5wm4f7cys-python3.8-argon2_cffi-19.2.0.drv",
  "/nix/store/1nvy9l90fpgs6yxpnh8ji5xfjspdbfhj-python3.8-colorcet-2.0.2.drv",
  "/nix/store/1q03fhv2vz7hzspfkk84vbairxrw3m96-python3.8-decorator-4.4.2.drv",
  "/nix/store/1q05lwd3vy30jlzqbc6l3i1lmq63j998-python3.8-seapy-dev.drv",
  "/nix/store/1qfxq056f8245gkjaps9jgzwi2hwnzl0-python3.8-acoustics-0.2.4.post0.drv",
  "/nix/store/1qlxvwbif456w533h62cy0k3s107f2f5-python3.8-PyYAML-5.3.1.drv",
  "/nix/store/22ja5cm07q516fiq1n4psi0yncibhvbd-python3.8-appdirs-1.4.4.drv",
  "/nix/store/29r49aa4sz6hypb3gv5sdw330vj2j2ii-python3.8-numpy-1.19.1.drv",
  "/nix/store/2h312vy4zc60fq48k6wwxb8sanlw4gnk-python3.8-webencodings-0.5.1.drv",
  "/nix/store/2s79596qplawrsvhjlhahigz3xgzax1g-python3.8-chardet-3.0.4.drv",
  "/nix/store/2yd64nbhn6xw6z2c83bnp96nvg5dk501-python3.8-toml-0.10.1.drv",
  "/nix/store/3k3pz3bgdxx84s8v04ajfznj3jxhrr1z-python3.8-zarr-2.4.0.drv",
  "/nix/store/3vgc68qbg9c5qhb18xc41ihaqw0bng6l-python3.8-setuptools-47.3.1.drv",
  "/nix/store/47gxh3n18rnqczsbqq6wgy4j8rd0kyla-python3.8-pyviz_comms-0.7.6.drv",
  "/nix/store/49y7xh42sk9xg0yp7i76ljjin2p2iklv-python3.8-apsw-3.33.0-r1.drv",
  "/nix/store/49zjibh5y3bpl537rh5wvcniag1fzw0i-python3.8-pysocks-1.7.1.drv",
  "/nix/store/4b4xvvkx7mjjfclizwx5dxljmlkvb8nq-python3.8-pbr-5.4.5.drv",
  "/nix/store/4gr6j6y175gi7nb5csldnmvbcik2b2n1-python3.8-py-1.9.0.drv",
  "/nix/store/4k0mbw4zf0vfh9vmvykkib52zvc78qbh-python3.8-pyjson5-0.8.5.drv",
  "/nix/store/4nsb5z8s0z7kzbwir82bp31xkqycrj9f-python3.8-panel-0.9.7.drv",
  "/nix/store/4qry96ap0kpkjwjlsyc8p3m3hh6pg5pv-bash-4.4-p23.drv",
  "/nix/store/5985r8irqxjm9hy2z2f0ci6hxv7ns1b6-python3.8-packaging-20.4.drv",
  "/nix/store/5nyhnmnisk3qvhca4gi28ww0fn3rc13c-python3.8-prometheus_client-0.8.0.drv",
  "/nix/store/5ssp2538riiz01yaikxl2sr72q6gzfa8-python3.8-dill-0.3.1.1.drv",
  "/nix/store/5v67yv9gfn31gnlpi5jkwf822j1lly30-python3.8-xarray-0.16.0.drv",
  "/nix/store/61krg8w5f0sjhhw63hjcss0sc8b2n5ai-python3.8-mock-4.0.2.drv",
  "/nix/store/62qdh9qc8f2jzmica8wr6w13jli2yhgz-python3.8-Bottleneck-1.3.2.drv",
  "/nix/store/65xv6ywyil2r90dc4anr0winvjm6kjaw-python3.8-pyzmq-19.0.2.drv",
  "/nix/store/6a688yfdk9fskrk6myk2q671aphrxxxs-python3.8-monotonic-1.5.drv",
  "/nix/store/6ik4ci6d5cy0rymrnqypq4xkl6ls9h6q-stdenv-linux.drv",
  "/nix/store/79i1pnazvvh4xsq77v9x5p2n7y1nd6hw-python3.8-lxml-4.5.2.drv",
  "/nix/store/7gy1l3w67c6ha3vis94x22jddg2lswx2-python3.8-xlwt-1.3.0.drv",
  "/nix/store/7ymbmx3v3a7hv56v0mng7qpmbhl63nxb-python3.8-dask-2.22.0.drv",
  "/nix/store/80pzh07z7qxq1j6v4bnj1qmrv9arwjmj-python3.8-pytest-5.4.3.drv",
  "/nix/store/877v1y795mz5qa2mji8mrrm6an7ryif8-python3.8-numba-0.51.1.drv",
  "/nix/store/8921ysf7srsn78cdkj4xpj32nghm6i6l-python3.8-MarkupSafe-1.1.1.drv",
  "/nix/store/8dadhhj8lzl87pvzz0m96fx3ck4cdcrw-python3.8-scipy-1.5.2.drv",
  "/nix/store/8haviy9cs7frjf7rhdksx8slcl8hng75-python3.8-SQLAlchemy-1.3.19.drv",
  "/nix/store/8kkcb5n71i2mnhpvvzfllmmcjwx7a8c6-python3.8-bokeh-2.1.1.drv",
  "/nix/store/8q581m4rpbq4jzj1hyjdlz1ia0wms33a-python3.8-pexpect-4.8.0.drv",
  "/nix/store/8xd835wxssmwp40krkm80l297skk1shq-python3.8-holoviews-1.13.3.drv",
  "/nix/store/900xv5xhja6hdz2hw3ad4rph1dqwjr5s-python3.8-olefile-0.46.drv",
  "/nix/store/96g7k8bd2ccig398zjzzyjy19gwmz6h7-python3.8-netCDF4-1.5.4.drv",
  "/nix/store/9dxid32d73fy7nmb4szv5b3sfk7r6dwf-python3.8-jdcal-1.4.1.drv",
  "/nix/store/9nbs7bs15pwrbbzfr693pi63vhjlvn30-python3.8-requests-2.24.0.drv",
  "/nix/store/a1jamqf44ak8ziw5797iw3awinv4qrz2-python3.8-jupyterlab-2.2.6.drv",
  "/nix/store/a64dpdms3qpssd5q78w8ci532jiv60fx-python3.8-tornado-6.0.4.drv",
  "/nix/store/axl3344gmxfvlxz7zbvi0jdxck1bvy6n-python3.8-pycparser-2.20.drv",
  "/nix/store/b6df7clg5j3jcg2a6w3mk0zhja021z1q-python3.8-pandas-1.1.1.drv",
  "/nix/store/bcsmb2b7ajbwnm7yhhjsmk3i6864pnvh-python3.8-pyrsistent-0.16.0.drv",
  "/nix/store/bdl756qayv4dhafql5hj7zknqsbv6fya-python3.8-tqdm-4.48.2.drv",
  "/nix/store/bfm575p96hn1jkjyfsgdlgjx31ar58rr-python3.8-beautifulsoup4-4.9.1.drv",
  "/nix/store/bmd6p38sqmp98m5n2ch3bj0v5z3y05vd-python3.8-xlrd-1.2.0.drv",
  "/nix/store/bwh15g23w6hkbk9vyrg2pb4arm0cglwz-python3.8-pickleshare-0.7.5.drv",
  "/nix/store/c1i0yk1pmiadgx6aridffi95wmzdvgv2-python3.8-notebook-6.1.3.drv",
  "/nix/store/c4ypmfjyvkn4f4wc3k9d3rdbph4qg5hg-python3.8-six-1.15.0.drv",
  "/nix/store/c85siklx3dlnw0www46naw6bggiqdngx-python3.8-entrypoints-0.3.drv",
  "/nix/store/ci0zqd3fs3w6sr95706aasqx9lzixvfk-python3.8-pytz-2020.1.drv",
  "/nix/store/clqqjrhva0289yiy0sjy5a4p973gnsgl-python3.8-jupyter_client-6.1.7.drv",
  "/nix/store/ddwiazld6c7rrzrnfcv0gxhz7pi7i5sc-python3.8-cloudpickle-1.5.0.drv",
  "/nix/store/f3fqq9wwslbkb3xks7bchn56869ibkkb-hook.drv",
  "/nix/store/f4w7zw2nc89zb92df3gcx4vws5cf5v1c-python3.8-path.py-12.0.1.drv",
  "/nix/store/f8bxxr5yhkxckbib0sy26s6db4rlgqd3-python3.8-pyasn1-0.4.8.drv",
  "/nix/store/fqagi5sfbarf5v4w1ax4amzld2hrcijw-python3.8-seaborn-0.10.1.drv",
  "/nix/store/fqrid483w95nxbh85ng0cai97z2pq38k-python3.8-atomicwrites-1.4.0.drv",
  "/nix/store/fs457c6xqh6sb0ngd59sxbcgfhvq60xs-python3.8-cffi-1.14.2.drv",
  "/nix/store/g5ql2bff3ds7g7s8g13fkjbbzhvgs2pj-python3.8-hvplot-0.6.0.drv",
  "/nix/store/gnzdf39jqx1s0g4ll1w5a72g5i76jgmx-python3.8-jedi-2020-08-06.drv",
  "/nix/store/hfhdlrm7n9ax3d4x968hnhcl5hn1wn4c-python3.8-pluggy-0.13.1.drv",
  "/nix/store/hsv6944z8s57scwa6xkpmhcvv2z3q6yf-python3.8-prompt_toolkit-3.0.6.drv",
  "/nix/store/hy0xmf24yz7nxwnb9rlb8k2frl42h8sk-python3.8-peewee-3.13.3.drv",
  "/nix/store/hzdk0fhfpharsp5icm2d3z2pwv9za89k-python3.8-backcall-0.2.0.drv",
  "/nix/store/iw07ra8g05m97xwlwfmvhrpahssys8zp-python3.8-jsonschema-3.2.0.drv",
  "/nix/store/j5pqp7jdl17acbc36ziyr5ky5fan022f-python3.8-Pygments-2.6.1.drv",
  "/nix/store/j9kgsqjrs4qqxqrynssqw3nlsppn4cmw-python3.8-partd-1.1.0.drv",
  "/nix/store/jdz6l9y9dgjzybg1gpfy3l38rp0j7bz3-python3.8-ipykernel-5.2.1.drv",
  "/nix/store/k6fvlqr3mlr27gsjdfvxwyaw6lgrwjns-python3.8-h5netcdf-0.8.1.drv",
  "/nix/store/kalaf6cm7agp9v7zi85w45w6xznhbngs-python3.8-pyct-0.4.6.drv",
  "/nix/store/kccp4c23nzbhc6fnaphr1wcwbz51nipb-python3.8-numcodecs-0.6.4.drv",
  "/nix/store/kcs1cg0wr2yrixh22nv8j3pn2fczra45-python3.8-h5py-2.9.0.drv",
  "/nix/store/kh6s26p8r82f6k0dymxgv5s8k7s7mfcv-python3.8-Markdown-3.2.2.drv",
  "/nix/store/khcsnxx14d5232vd90y2h8k1jfcfp9lh-python3.8-html5lib-1.1.drv",
  "/nix/store/l20kvwj37iq562l1jw19wx7920chycjm-python3.8-numexpr-2.7.1.drv",
  "/nix/store/l3p4vfcs3lnk2y25l2gjyhw0v8lzk97c-python3.8-mistune-0.8.4.drv",
  "/nix/store/l5fhajqvy4837hrwvp9w8ljgy403ly69-python3.8-pyOpenSSL-19.1.0.drv",
  "/nix/store/lihafnyvwxswj6m16hnhfv5826dmp7ml-python3.8-Send2Trash-1.5.0.drv",
  "/nix/store/lk7x8fmcfk9qfhzz8dh4rwa7x3xm2xb0-python3.8-more-itertools-8.4.0.drv",
  "/nix/store/lq21qhyvb2q3d6vfcydvvhlb6g18rz01-python3.8-python-dateutil-2.8.1.drv",
  "/nix/store/lzha097fl12mja84nrjqqr2yirbam93s-python3.8-psycopg2-2.8.5.drv",
  "/nix/store/lznmyjq3yv627blmi9bp7mp9bj8jh1r2-python3.8-urllib3-1.25.10.drv",
  "/nix/store/m0b7zlgm37g3vljzvxhm5np3dvl3149l-python3.8-zipp-3.1.0.drv",
  "/nix/store/m0r8n5mjkym3i7r057rfbb1pxggsv250-python3.8-asciitree-0.3.3.drv",
  "/nix/store/mchf2whprsrkalixs1pii1y2l1d297hr-python3.8-jupyter_core-4.6.3.drv",
  "/nix/store/mrapfj50v7cis2cm38ghiv9vag8wjarr-python3.8-importlib-metadata-1.7.0.drv",
  "/nix/store/mssm05sn3dvm35qlxy0plswlvqkhx0fz-python3.8-networkx-2.4.drv",
  "/nix/store/n0c4qwz0y4mqvhq6rkyhcdahss742nag-python3.8-selenium-3.141.0.drv",
  "/nix/store/ni2kcvkbjzrwsmqnh7bkc04zbjysm1yk-python3.8-tables-3.6.1.drv",
  "/nix/store/p08bl3ajz9pdym94anj2man50wqhw2k1-python3.8-attrs-19.3.0.drv",
  "/nix/store/pdnl9ciyzri5dhyr0p38rrd495q2ckxb-python3.8-cftime-1.2.1.drv",
  "/nix/store/pfh31mik59lgj9a3srnf9dqpl1l83pxl-python3.8-fasteners-0.15.drv",
  "/nix/store/pwjisxq618hl0g533cc5v48bzvadk9zx-python3.8-tkinter-3.8.5.drv",
  "/nix/store/pxymaq2xl10sr6hkhf2sz8fdj4sj7c02-python3.8-ptyprocess-0.6.0.drv",
  "/nix/store/q1q5dsc3pcx10clb38gyrbrgivl47kl8-python3-3.8.5.drv",
  "/nix/store/q30gsd85k5g75ic4xjxma4djfli3shbd-python3.8-matplotlib-3.3.1.drv",
  "/nix/store/q4ypk29g042dvp8nq1l2m2csa2jfzpax-python3.8-line_profiler-3.0.2.drv",
  "/nix/store/q9rr3ii1zypvqrg231cp8rh0skklqav0-python3.8-nbformat-5.0.7.drv",
  "/nix/store/qjiv1aqr4sv4dn66p9p4q6jh3fi9mgph-python3.8-soupsieve-2.0.1.drv",
  "/nix/store/qqm826pz6m6fxg18i9qd129dj4is4zy2-python3.8-pandocfilters-1.4.2.drv",
  "/nix/store/qry9xnl9icncknqbfhcld36d4mn3vfw7-python3.8-llvmlite-0.34.0.drv",
  "/nix/store/qsldb0vqrrs53grknrjkzq5v366ipcn9-perl-5.32.0.drv",
  "/nix/store/qyplnd6z330zhcrlj5f9dbm1dqbg4bbk-python3.8-msgpack-1.0.0.drv",
  "/nix/store/r6zc3a1rvyv89kh0a38kp8q20mr935y4-python3.8-traitlets-4.3.3.drv",
  "/nix/store/rppp5q1fk64sapikha3l3ldz7sid4v75-python3.8-param-1.9.3.drv",
  "/nix/store/rxg12jhj9y7yfapiwnnns30n9x15f80l-python3.8-Jinja2-2.11.2.drv",
  "/nix/store/s9sjnvfv0ijx2nkd1pd6gmqj1fp39xan-python3.8-ipython_genutils-0.2.0.drv",
  "/nix/store/sbbpvl8vmp2rzizl2fcd4h0m9qvhih48-python3.8-docutils-0.16.drv",
  "/nix/store/sh3y9c9pm8lwj13sr2cni6jfyg6i1j4q-python3.8-Pillow-7.2.0.drv",
  "/nix/store/sh4r5k2i6g1ian1pfynfk74px6bwqdmp-builder.pl.drv",
  "/nix/store/shvhb5dgj7g4jcagmqr88qi0imma0c95-python3.8-typing_extensions-3.7.4.3.drv",
  "/nix/store/ss9knlli5f0hf64xygpx82gkbamc0yhq-python3.8-setuptools_scm-4.1.2.drv",
  "/nix/store/sy93f6s0il9xmfna6qngx37rr43bqwqp-python3.8-fsspec-0.7.4.drv",
  "/nix/store/v29d09v00bdc65b4ykqgpbmbkclqm1lk-python3.8-ipython-7.17.0.drv",
  "/nix/store/v942whac5n10s7hvnrbrr9irzbbbgmsf-python3.8-wcwidth-0.2.5.drv",
  "/nix/store/wb2h7m25slc3gsvphw8wrr6zf0sa9sdh-python3.8-pyparsing-2.4.6.drv",
  "/nix/store/whcahjlyzvryirrppdgw7zjs6wdpdg8i-python3.8-bleach-3.1.5.drv",
  "/nix/store/whp5xvsfs6l0m63f4vy79ha4akxbjcbm-python3.8-locket-0.2.0.drv",
  "/nix/store/wlgp9v2cfv9hnf8rypmjgsw6vb14xmxl-python3.8-certifi-2020.6.20.drv",
  "/nix/store/wnh4f2y0fr5q8kmi1majp1d07lg5pvdi-python3.8-toolz-0.10.0.drv",
  "/nix/store/wshv4p0mm61n5byqvrcf885ldl3l6nc4-python3.8-cycler-0.10.0.drv",
  "/nix/store/wxdbxw0hqd46ld1ha01v1ralkh6l01qx-python3.8-tabulate-0.8.7.drv",
  "/nix/store/xw0jyf81s8cg10lvk58qdb7azl0bix1k-python3.8-kiwisolver-1.2.0.drv",
  "/nix/store/y8w947frnb2wny9brv24aw3p7yzfvvdz-python3.8-terminado-0.8.3.drv",
  "/nix/store/y99463wmw29n8izgf8fpq3w4r9pwkgxd-python3.8-parso-0.8.0.drv",
  "/nix/store/z0p7qgkvj837c20hqaddfxcxkagr1lb9-python3.8-idna-2.10.drv",
  "/nix/store/zafx0kcb7bclqh9m9p2m411d4y35491p-python3.8-testpath-0.4.4.drv",
  "/nix/store/zi7j4rm8py5x1i89ywq727d6lpmz5zvw-python3.8-defusedxml-0.6.0.drv",
  "/nix/store/zkr778pi7srk8xsjndamhhdsq0ghxkyr-python3.8-cryptography-3.1.drv"
]
```

#### Description of expected behavior and the observed behavior
Plotting with matplotlib as image a 2-dimensional array that has a datetime range as index raises.

```
TypeError: ufunc 'isfinite' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''
```

#### Complete, minimal, self-contained example code that reproduces the issue

```py
import datetime
import holoviews as hv
import hvplot.xarray
import numpy as np
import pandas as pd
import xarray as xr

hv.extension('matplotlib')

arr = xr.DataArray(np.ones((5, 4)), dims=["a","b"], coords={
    "a": pd.date_range(start=datetime.date(2020, 9, 1), end=datetime.date(2020, 10, 1), periods=5), # works fine without date range
    "b": np.arange(4),
})

arr.hvplot("a", "b")

```

#### Stack traceback and/or browser JavaScript console output

```
Traceback (most recent call last):

  File "/nix/store/42yh96csb0wn65xcbkldvlnrjkrk5sxf-python3-3.8.5-env/lib/python3.8/site-packages/holoviews/plotting/mpl/element.py", line 513, in initialize_plot
    handles = self.init_artists(ax, plot_data, plot_kwargs)

  File "/nix/store/42yh96csb0wn65xcbkldvlnrjkrk5sxf-python3-3.8.5-env/lib/python3.8/site-packages/holoviews/plotting/mpl/element.py", line 531, in init_artists
    artist = plot_fn(*plot_args, **plot_kwargs)

  File "/nix/store/42yh96csb0wn65xcbkldvlnrjkrk5sxf-python3-3.8.5-env/lib/python3.8/site-packages/matplotlib/__init__.py", line 1438, in inner
    return func(ax, *map(sanitize_sequence, args), **kwargs)

  File "/nix/store/42yh96csb0wn65xcbkldvlnrjkrk5sxf-python3-3.8.5-env/lib/python3.8/site-packages/matplotlib/axes/_axes.py", line 5533, in imshow
    im.set_extent(im.get_extent())

  File "/nix/store/42yh96csb0wn65xcbkldvlnrjkrk5sxf-python3-3.8.5-env/lib/python3.8/site-packages/matplotlib/image.py", line 948, in set_extent
    self.axes.update_datalim(corners)

  File "/nix/store/42yh96csb0wn65xcbkldvlnrjkrk5sxf-python3-3.8.5-env/lib/python3.8/site-packages/matplotlib/axes/_base.py", line 2147, in update_datalim
    if not np.any(np.isfinite(xys)):

TypeError: ufunc 'isfinite' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''
```

Original ticket on matplotlib tracker https://github.com/matplotlib/matplotlib/issues/18524. Possibly related to https://github.com/holoviz/holoviews/pull/2715.

**Comment by jlstevens** [comment]
Very odd! 

From the issue title, you imply that this is only a problem with the matplotlib backend? Have you tried it with the Bokeh backend?

One thing that would really help us decide whether this is a HoloViews issue or a matplotlib limitation would be for you to supply us with a matplotlib example plot that successfully uses `pd.date_range`.

**Comment by FRidh** [comment]
It works fine with the bokeh backend, just not with the matplotlib backend.

Simple example of a curve with dates on the x-axis:
```py
import numpy as np
import pandas as pd
index = pd.date_range("2020-09-01", "2020-10-01")
series = pd.Series(np.random.randn(len(index)), index=index)
series.plot()
```

Example of a mesh with dates on both x and y-axis.
```py
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
index1 = pd.date_range("2020-09-01", "2020-10-01")
index2 = pd.date_range("2019-09-01", "2019-10-01")
plt.pcolormesh(index1, index2, np.random.randn(len(index1), len(index2)))
```
