### ISSUE TITLE
'tuple' object has no attribute 'get' holoviews 1.14.0

### ISSUE THREAD

**Issue by WesleyTheGeolien** [holoviz/holoviews#4763]
#### ALL software version info
holoviews: 1.14.0

#### Description of expected behavior and the observed behavior
Whilst running the [Linked Brushing Notebook](https://github.com/holoviz/holoviews/blob/master/examples/user_guide/Linked_Brushing.ipynb) from your examples I get the following Traceback for the cell `link_selections(layout).opts(opts.Points(width=200, height=200)).cols(6)`:
```
Traceback (most recent call last):
  File "/opt/conda/envs/python/lib/python3.7/site-packages/pyviz_comms/__init__.py", line 316, in _handle_msg
    self._on_msg(msg)
  File "/opt/conda/envs/python/lib/python3.7/site-packages/holoviews/plotting/bokeh/callbacks.py", line 163, in on_msg
    raise e
  File "/opt/conda/envs/python/lib/python3.7/site-packages/holoviews/plotting/bokeh/callbacks.py", line 155, in on_msg
    Stream.trigger(streams)
  File "/opt/conda/envs/python/lib/python3.7/site-packages/holoviews/streams.py", line 171, in trigger
    subscriber(**dict(union))
  File "/opt/conda/envs/python/lib/python3.7/site-packages/holoviews/streams.py", line 834, in perform_update
    self.event()
  File "/opt/conda/envs/python/lib/python3.7/site-packages/holoviews/streams.py", line 415, in event
    self.trigger([self])
  File "/opt/conda/envs/python/lib/python3.7/site-packages/holoviews/streams.py", line 171, in trigger
    subscriber(**dict(union))
  File "/opt/conda/envs/python/lib/python3.7/site-packages/holoviews/streams.py", line 919, in perform_update
    self.event()
  File "/opt/conda/envs/python/lib/python3.7/site-packages/holoviews/streams.py", line 415, in event
    self.trigger([self])
  File "/opt/conda/envs/python/lib/python3.7/site-packages/holoviews/streams.py", line 171, in trigger
    subscriber(**dict(union))
  File "/opt/conda/envs/python/lib/python3.7/site-packages/holoviews/streams.py", line 834, in perform_update
    self.event()
  File "/opt/conda/envs/python/lib/python3.7/site-packages/holoviews/streams.py", line 415, in event
    self.trigger([self])
  File "/opt/conda/envs/python/lib/python3.7/site-packages/holoviews/streams.py", line 171, in trigger
    subscriber(**dict(union))
  File "/opt/conda/envs/python/lib/python3.7/site-packages/holoviews/plotting/plot.py", line 244, in refresh
    raise e
  File "/opt/conda/envs/python/lib/python3.7/site-packages/holoviews/plotting/plot.py", line 240, in refresh
    self._trigger_refresh(stream_key)
  File "/opt/conda/envs/python/lib/python3.7/site-packages/holoviews/plotting/plot.py", line 257, in _trigger_refresh
    self.update(key)
  File "/opt/conda/envs/python/lib/python3.7/site-packages/holoviews/plotting/plot.py", line 981, in update
    item = self.__getitem__(key)
  File "/opt/conda/envs/python/lib/python3.7/site-packages/holoviews/plotting/plot.py", line 446, in __getitem__
    self.update_frame(frame)
  File "/opt/conda/envs/python/lib/python3.7/site-packages/holoviews/plotting/bokeh/element.py", line 2388, in update_frame
    ranges = self.compute_ranges(range_obj, key, ranges)
  File "/opt/conda/envs/python/lib/python3.7/site-packages/holoviews/plotting/plot.py", line 640, in compute_ranges
    prev_frame)
  File "/opt/conda/envs/python/lib/python3.7/site-packages/holoviews/plotting/plot.py", line 873, in _compute_group_range
    ids = values.get('id')
AttributeError: 'tuple' object has no attribute 'get'
```

#### Complete, minimal, self-contained example code that reproduces the issue
 [Linked Brushing Notebook](https://github.com/holoviz/holoviews/blob/master/examples/user_guide/Linked_Brushing.ipynb)
execute all from start (problem in input 5)

**Comment by philippjfr** [comment]
Fixed in https://github.com/holoviz/holoviews/pull/4742, release will happen today or tomorrow.
