### ISSUE TITLE
Error using hv.Image

### ISSUE THREAD

**Issue by sonal-ssj** [holoviz/holoviews#4846]
#### software version info
hv: 1.14.1
python: 3.7.6
browser: Firefox

#### Description of expected behavior and the observed behavior
Cannot run hv.Image example

#### Complete, minimal, self-contained example code that reproduces the issue

```
ls = np.linspace(0, 10, 200)
xx, yy = np.meshgrid(ls, ls)

bounds=(-1,-1,1,1)   # Coordinate system: (left, bottom, right, top)
img = hv.Image(np.sin(xx)*np.cos(yy), bounds=bounds)
img

```

#### Stack traceback and/or browser JavaScript console output

```
AttributeError [Call holoviews.ipython.show_traceback() for details]
'str' object has no attribute 'dataspecs'

$hv.ipython.show_traceback()
Traceback (most recent call last):
  File "/../miniconda3/envs/pytorch1.6_cuda10.2/lib/python3.7/site-packages/holoviews/plotting/bokeh/element.py", line 1359, in _init_glyphs
    self._update_glyph(renderer, properties, mapping, glyph, source, source.data)

  File "/../miniconda3/envs/pytorch1.6_cuda10.2/lib/python3.7/site-packages/holoviews/plotting/bokeh/element.py", line 1252, in _update_glyph
    dataspecs = glyph.dataspecs()

AttributeError: 'str' object has no attribute 'dataspecs'

```

**Comment by philippjfr** [comment]
See https://github.com/holoviz/holoviews/issues/4845. We'll release a new HoloViews with compatibility for Bokeh 2.3 in the coming days for now downgrade bokeh to 2.2.3.

**Comment by sonal-ssj** [comment]
Thanks for the quick reply, that worked!
