### ISSUE TITLE
Lasso select error should be non-fatal

### ISSUE THREAD

**Issue by jbednar** [holoviz/holoviews#4874]
Right now, if you select a lasso tool and make a selection on a plot using link_selections without having spatialpandas or shapely installed, it aborts with the message below.  It's fine for that functionality not to be available, but since I believe lasso select is typically available in the toolbar, it shouldn't be possible to make an app or Python process crash simply by selecting that tool and using it. I'd hope for a helpful warning and a no-op in that case, and then users could go back to the other supported tools for selection.

```
tornado.application - ERROR - Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOMainLoop object at 0x7f796b4efdc0>>, <Task finished name='Task-431' coro=<_needs_document_lock.<locals>._needs_document_lock_wrapper() done, defined at /home/jbednar/miniconda3/envs/holoviz/lib/python3.8/site-packages/bokeh/server/session.py:51> exception=CallbackError('linked_selection aborted because it could not display selection for all elements: Lasso selection on tabular data requires either spatialpandas or shapely to be available..')>)
Traceback (most recent call last):
  File "/home/jbednar/miniconda3/envs/holoviz/lib/python3.8/site-packages/holoviews/element/selection.py", line 88, in spatial_select_columnar
    from shapely.geometry import Point, Polygon
ModuleNotFoundError: No module named 'shapely'

During handling of the above exception, another exception occurred:
```

**Comment by philippjfr** [comment]
I really need an example here, in my testing this isn't fatal at all.

**Comment by jbednar** [comment]
I must have been confused about it being fatal. I guess the problem is just that it prints pages of error output, but it's actually not aborting despite all the tracebacks and exceptions listed? I can reproduce the error output using the https://examples.pyviz.org/glaciers/glaciers.html project.  If I run it as usual, it works for lasso selections:

```
~/examples/glaciers> anaconda-project run
...
2021-04-08 08:20:09,066 Starting Bokeh server version 2.2.3 (running on Tornado 6.1)
```

But if I then remove spatialpandas, it dumps lots of tracebacks when I lasso select rather than printing a friendly warning:


```
~/examples/glaciers> conda activate envs/default
(default) ~/examples/glaciers> conda uninstall spatialpandas
...
Executing transaction: done
(default) ~/examples/glaciers> panel serve glaciers.ipynb 
2021-04-08 08:22:41,967 Starting Bokeh server version 2.2.3 (running on Tornado 6.1)
2021-04-08 08:22:41,971 User authentication hooks NOT provided (default user enabled)
2021-04-08 08:22:41,974 Bokeh app running at: http://localhost:5006/glaciers
2021-04-08 08:22:41,974 Starting Bokeh server with process id: 49737
:Dataset   [x,y]   (avg_prcp,area_km2,latdeg,avg_temp_at_mean_elev,mean_elev) 213750 613225.6620000001
tornado.application - ERROR - Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOMainLoop object at 0x7f93215b2b90>>, <Task finished coro=<_needs_document_lock.<locals>._needs_document_lock_wrapper() done, defined at /Users/jbednar/examples/glaciers/envs/default/lib/python3.7/site-packages/bokeh/server/session.py:51> exception=CallbackError('linked_selection aborted because it could not display selection for all elements: Lasso selection on tabular data requires either spatialpandas or shapely to be available..')>)
Traceback (most recent call last):
  File "/Users/jbednar/examples/glaciers/envs/default/lib/python3.7/site-packages/holoviews/element/selection.py", line 83, in spatial_select_columnar
    from shapely.geometry import Point, Polygon
ModuleNotFoundError: No module named 'shapely'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/jbednar/examples/glaciers/envs/default/lib/python3.7/site-packages/holoviews/selection.py", line 482, in _select
    mask = selection_expr.apply(dataset, compute=False, keep_index=True, strict=False)
  File "/Users/jbednar/examples/glaciers/envs/default/lib/python3.7/site-packages/holoviews/util/transform.py", line 689, in apply
    kwargs, accessor, drange)
  File "/Users/jbednar/examples/glaciers/envs/default/lib/python3.7/site-packages/holoviews/util/transform.py", line 591, in _apply_fn
    data = fn(*args, **kwargs)
  File "/Users/jbednar/examples/glaciers/envs/default/lib/python3.7/site-packages/holoviews/element/selection.py", line 95, in spatial_select
    return spatial_select_columnar(xvals, yvals, geometry)
  File "/Users/jbednar/examples/glaciers/envs/default/lib/python3.7/site-packages/holoviews/element/selection.py", line 88, in spatial_select_columnar
    raise ImportError("Lasso selection on tabular data requires "
ImportError: Lasso selection on tabular data requires either spatialpandas or shapely to be available.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/jbednar/examples/glaciers/envs/default/lib/python3.7/site-packages/tornado/ioloop.py", line 741, in _run_callback
    ret = callback()
  File "/Users/jbednar/examples/glaciers/envs/default/lib/python3.7/site-packages/tornado/ioloop.py", line 765, in _discard_future_result
    future.result()
  File "/Users/jbednar/examples/glaciers/envs/default/lib/python3.7/site-packages/bokeh/server/session.py", line 71, in _needs_document_lock_wrapper
    result = await result
  File "/Users/jbednar/examples/glaciers/envs/default/lib/python3.7/site-packages/tornado/gen.py", line 216, in wrapper
    result = ctx_run(func, *args, **kwargs)
  File "/Users/jbednar/examples/glaciers/envs/default/lib/python3.7/site-packages/holoviews/plotting/bokeh/callbacks.py", line 466, in process_on_event
    self.on_msg(msg)
  File "/Users/jbednar/examples/glaciers/envs/default/lib/python3.7/site-packages/holoviews/plotting/bokeh/callbacks.py", line 161, in on_msg
    raise e
  File "/Users/jbednar/examples/glaciers/envs/default/lib/python3.7/site-packages/holoviews/plotting/bokeh/callbacks.py", line 155, in on_msg
    Stream.trigger(streams)
  File "/Users/jbednar/examples/glaciers/envs/default/lib/python3.7/site-packages/holoviews/streams.py", line 171, in trigger
    subscriber(**dict(union))
  File "/Users/jbednar/examples/glaciers/envs/default/lib/python3.7/site-packages/holoviews/streams.py", line 834, in perform_update
    self.event()
  File "/Users/jbednar/examples/glaciers/envs/default/lib/python3.7/site-packages/holoviews/streams.py", line 415, in event
    self.trigger([self])
  File "/Users/jbednar/examples/glaciers/envs/default/lib/python3.7/site-packages/holoviews/streams.py", line 171, in trigger
    subscriber(**dict(union))
  File "/Users/jbednar/examples/glaciers/envs/default/lib/python3.7/site-packages/holoviews/streams.py", line 919, in perform_update
    self.event()
  File "/Users/jbednar/examples/glaciers/envs/default/lib/python3.7/site-packages/holoviews/streams.py", line 415, in event
    self.trigger([self])
  File "/Users/jbednar/examples/glaciers/envs/default/lib/python3.7/site-packages/holoviews/streams.py", line 171, in trigger
    subscriber(**dict(union))
  File "/Users/jbednar/examples/glaciers/envs/default/lib/python3.7/site-packages/holoviews/streams.py", line 834, in perform_update
    self.event()
  File "/Users/jbednar/examples/glaciers/envs/default/lib/python3.7/site-packages/holoviews/streams.py", line 415, in event
    self.trigger([self])
  File "/Users/jbednar/examples/glaciers/envs/default/lib/python3.7/site-packages/holoviews/streams.py", line 171, in trigger
    subscriber(**dict(union))
  File "/Users/jbednar/examples/glaciers/envs/default/lib/python3.7/site-packages/holoviews/streams.py", line 834, in perform_update
    self.event()
  File "/Users/jbednar/examples/glaciers/envs/default/lib/python3.7/site-packages/holoviews/streams.py", line 413, in event
    skip = self.update(**kwargs)
  File "/Users/jbednar/examples/glaciers/envs/default/lib/python3.7/site-packages/holoviews/streams.py", line 430, in update
    self._set_stream_parameters(**transformed)
  File "/Users/jbednar/examples/glaciers/envs/default/lib/python3.7/site-packages/holoviews/streams.py", line 407, in _set_stream_parameters
    self.param.set_param(**kwargs)
  File "/Users/jbednar/examples/glaciers/envs/default/lib/python3.7/site-packages/param/parameterized.py", line 1472, in set_param
    self_._batch_call_watchers()
  File "/Users/jbednar/examples/glaciers/envs/default/lib/python3.7/site-packages/param/parameterized.py", line 1611, in _batch_call_watchers
    self_._execute_watcher(watcher, events)
  File "/Users/jbednar/examples/glaciers/envs/default/lib/python3.7/site-packages/param/parameterized.py", line 1573, in _execute_watcher
    watcher.fn(*args, **kwargs)
  File "/Users/jbednar/examples/glaciers/envs/default/lib/python3.7/site-packages/holoviews/selection.py", line 370, in selection_expr_changed
    inst.selection_expr = new_selection_expr
  File "/Users/jbednar/examples/glaciers/envs/default/lib/python3.7/site-packages/param/parameterized.py", line 318, in _f
    return f(self, obj, val)
  File "/Users/jbednar/examples/glaciers/envs/default/lib/python3.7/site-packages/param/parameterized.py", line 936, in __set__
    obj.param._call_watcher(watcher, event)
  File "/Users/jbednar/examples/glaciers/envs/default/lib/python3.7/site-packages/param/parameterized.py", line 1591, in _call_watcher
    self_._execute_watcher(watcher, (event,))
  File "/Users/jbednar/examples/glaciers/envs/default/lib/python3.7/site-packages/param/parameterized.py", line 1573, in _execute_watcher
    watcher.fn(*args, **kwargs)
  File "/Users/jbednar/examples/glaciers/envs/default/lib/python3.7/site-packages/param/parameterized.py", line 520, in caller
    return function()
  File "/Users/jbednar/examples/glaciers/envs/default/lib/python3.7/site-packages/param/parameterized.py", line 351, in _depends
    return func(*args,**kw)
  File "/Users/jbednar/examples/glaciers/envs/default/lib/python3.7/site-packages/holoviews/selection.py", line 301, in _update_pipes
    sel_ds = SelectionDisplay._select(ds, sel_expr, self._cache)
  File "/Users/jbednar/examples/glaciers/envs/default/lib/python3.7/site-packages/holoviews/selection.py", line 491, in _select
    "display selection for all elements: %s." % e)
holoviews.core.options.CallbackError: linked_selection aborted because it could not display selection for all elements: Lasso selection on tabular data requires either spatialpandas or shapely to be available..
```

So I'll change the title to request a friendly and concise warning rather than a massive traceback.

**Comment by philippjfr** [comment]
>So I'll change the title to request a friendly and concise warning rather than a massive traceback.

Seems like an error is the correct thing to raise here, the requested operation is actually failing which isn't a "friendly warning" scenario imo.

**Comment by philippjfr** [comment]
The change I would maybe suggest is improving the docs about what's required for lasso select and then only adding the lasso select tool if the required libraries are available.

**Comment by jbednar** [comment]
I think raising an exception should be reserved for either a user's programming mistake that we detect, or a scenario where it's really not feasible to go forward as a functioning program. Neither of those apply here; it's clear how the rest of the plot should operate even if lasso select is not available, and it not being available isn't the fault of the user/programmer, but of the larger machine environment. So I'd want the running Bokeh plot not to fail because of such a limitation of the environment; the plot should still otherwise be usable in that context and should not break because the user selected lasso without having the suitable external package installed.  Ideally, yes, the lasso select tool shouldn't even be visible, advertising functionality that's not actually available, so I agree that's the best solution. If it's impractical to suppress the icon, _at_ _least_ the plot shouldn't crash when the user selects lasso; I'd want to see a warning on the console at worst, and the user can simply move on to some supported functionality for that plot.

**Comment by jbednar** [comment]
Note that I'm not objecting to that particular operation raising an exception internally. It's appropriate for that particular operation to raise an exception if it encounters a condition that prevents it from being carried out. Still, if that operation has an exception that's expected in normal, non-error cases, it should be caught _at_ _some_ _level_ rather than result in a traceback for the end user. The end user shouldn't see it as an error condition, but as an indication that they may or may not want to install the indicated libraries if they want lasso support.

**Comment by philippjfr** [comment]
>at least the plot shouldn't crash

But it doesn't crash does it? It simply aborts the lasso selection with an error, which is correct. You could definitely argue that a user shouldn't see a traceback but the end effect is the same, the selection is aborted, that's all.

**Comment by jbednar** [comment]
My initial message states that the Python process aborts, i.e. that it prints the message indicated and then the plot no longer works again. I haven't tried to reproduce that recently, though.

**Comment by philippjfr** [comment]
That seems far more worrying than the traceback itself.

**Comment by jbednar** [comment]
Hence this issue asking that this condition only generate  a warning, not aborting. Sorry if that aspect of the request was not obvious in the issue as originally raised.
