### ISSUE TITLE
Bokeh not rendering in Jupyter Lab

### ISSUE THREAD

**Issue by Sidney-Bishop** [holoviz/holoviews#4875]
Hi

similar to this issue: #10002 ( thanks to all for detailed info )

I've encountered a similar problem on MAC OS Big Sur 11.2 ( see screen grab below )

**However**, I don't have any markdown code mentioning Bokeh

Python version      :  3.8.8 (default, Feb 24 2021, 13:46:16) 
IPython version     :  7.21.0
Tornado version     :  6.1
Bokeh version       :  **2.3.0**
Holoviews version: **1.14.2**
BokehJS static path :  /Users/user1/opt/anaconda3/lib/python3.8/site-packages/bokeh/server/static
node.js version     :  (not installed)
npm version         :  (not installed)

I get the same error in Jupyter Lab.

Any suggestions would be appreciated.

<img width="1401" alt="Screenshot 2021-03-29 at 22 12 48" src="https://user-images.githubusercontent.com/7266636/112900888-f48c3900-90db-11eb-83f2-b23df2f3750f.png">

**Comment by philippjfr** [comment]
Was definitely hoping this issue would go away. First steps I'd try are:

1. Clear the notebook
2. Save the notebook
3. Reload the page
4. Report the `Bokeh.version` reported in the browsers JS console

**Comment by Sidney-Bishop** [comment]
My error has changes to ( see attached screen grab )

**Javascript error adding output!
Error: Cannot find module '@bokehjs/styles/buttons'
See your browser Javascript console for more details.**

I've included the console output below but Im unable to find the Bokeh.version in the JS console. I've tried filtering for it. 

**NOTE**: I was reading https://github.com/bokeh/bokeh/issues/10523 and so tried to install nodejs and npm as per below
```
conda install -c conda-forge nodejs
npm install -g npm@7
```

This might not have helped 

```
actions jupyter-notebook:find-and-replace does not exist, still binding it in case it will be defined later...
MenuBar.bind_events @ main.min.js?v=7af39fe9ec3585e958e8637ace5e96fe0bf3ced51a8b8b5875c571f941299779fe746bf74f02bab0f3c6e08281d6ecadafcb5b08120e98f081c9c7dd824bdfdc:45677
main.min.js?v=7af39fe9ec3585e958e8637ace5e96fe0bf3ced51a8b8b5875c571f941299779fe746bf74f02bab0f3c6e08281d6ecadafcb5b08120e98f081c9c7dd824bdfdc:24190 load_extensions Arguments(2)0: "jupyter_bokeh/extension"1: "jupyter-js-widgets/extension"callee: (...)length: 2Symbol(Symbol.iterator): ƒ values()get callee: ƒ ()set callee: ƒ ()__proto__: Object
main.min.js?v=7af39fe9ec3585e958e8637ace5e96fe0bf3ced51a8b8b5875c571f941299779fe746bf74f02bab0f3c6e08281d6ecadafcb5b08120e98f081c9c7dd824bdfdc:33602 Loaded moment locale en-gb
main.min.js?v=7af39fe9ec3585e958e8637ace5e96fe0bf3ced51a8b8b5875c571f941299779fe746bf74f02bab0f3c6e08281d6ecadafcb5b08120e98f081c9c7dd824bdfdc:24167 Loading extension: jupyter_bokeh/extension
main.min.js?v=7af39fe9ec3585e958e8637ace5e96fe0bf3ced51a8b8b5875c571f941299779fe746bf74f02bab0f3c6e08281d6ecadafcb5b08120e98f081c9c7dd824bdfdc:24167 Loading extension: jupyter-js-widgets/extension
main.min.js?v=7af39fe9ec3585e958e8637ace5e96fe0bf3ced51a8b8b5875c571f941299779fe746bf74f02bab0f3c6e08281d6ecadafcb5b08120e98f081c9c7dd824bdfdc:38824 Session: kernel_created (f3b77d8d-fc8b-4c7c-a185-2a6c44b3a820)
main.min.js?v=7af39fe9ec3585e958e8637ace5e96fe0bf3ced51a8b8b5875c571f941299779fe746bf74f02bab0f3c6e08281d6ecadafcb5b08120e98f081c9c7dd824bdfdc:37969 Starting WebSockets: ws://localhost:8890/api/kernels/054d4c37-938c-483e-bc09-6e4a2e50a8ac
main.min.js?v=7af39fe9ec3585e958e8637ace5e96fe0bf3ced51a8b8b5875c571f941299779fe746bf74f02bab0f3c6e08281d6ecadafcb5b08120e98f081c9c7dd824bdfdc:37612 Kernel: kernel_connected (054d4c37-938c-483e-bc09-6e4a2e50a8ac)
main.min.js?v=7af39fe9ec3585e958e8637ace5e96fe0bf3ced51a8b8b5875c571f941299779fe746bf74f02bab0f3c6e08281d6ecadafcb5b08120e98f081c9c7dd824bdfdc:37612 Kernel: kernel_ready (054d4c37-938c-483e-bc09-6e4a2e50a8ac)
VM29:1130 Bokeh: BokehJS plotting callback run at Tue Mar 30 2021 14:03:47 GMT+0100 (Irish Standard Time)
VM29:305 [bokeh] setting log level to: 'info'
main.min.js?v=7af39fe9ec3585e958e8637ace5e96fe0bf3ced51a8b8b5875c571f941299779fe746bf74f02bab0f3c6e08281d6ecadafcb5b08120e98f081c9c7dd824bdfdc:35621 Error: Cannot find module '@bokehjs/styles/buttons'
    at require (eval at append_javascript (main.min.js?v=7af39fe9ec3585e958e8637ace5e96fe0bf3ced51a8b8b5875c571f941299779fe746bf74f02bab0f3c6e08281d6ecadafcb5b08120e98f081c9c7dd824bdfdc:35619), <anonymous>:210:27)
    at Object._ (eval at append_javascript (main.min.js?v=7af39fe9ec3585e958e8637ace5e96fe0bf3ced51a8b8b5875c571f941299779fe746bf74f02bab0f3c6e08281d6ecadafcb5b08120e98f081c9c7dd824bdfdc:35619), <anonymous>:1072:112)
    at require (eval at append_javascript (main.min.js?v=7af39fe9ec3585e958e8637ace5e96fe0bf3ced51a8b8b5875c571f941299779fe746bf74f02bab0f3c6e08281d6ecadafcb5b08120e98f081c9c7dd824bdfdc:35619), <anonymous>:228:27)
    at Object._ (eval at append_javascript (main.min.js?v=7af39fe9ec3585e958e8637ace5e96fe0bf3ced51a8b8b5875c571f941299779fe746bf74f02bab0f3c6e08281d6ecadafcb5b08120e98f081c9c7dd824bdfdc:35619), <anonymous>:1033:412)
    at require (eval at append_javascript (main.min.js?v=7af39fe9ec3585e958e8637ace5e96fe0bf3ced51a8b8b5875c571f941299779fe746bf74f02bab0f3c6e08281d6ecadafcb5b08120e98f081c9c7dd824bdfdc:35619), <anonymous>:228:27)
    at Object._ (eval at append_javascript (main.min.js?v=7af39fe9ec3585e958e8637ace5e96fe0bf3ced51a8b8b5875c571f941299779fe746bf74f02bab0f3c6e08281d6ecadafcb5b08120e98f081c9c7dd824bdfdc:35619), <anonymous>:1032:79)
    at require (eval at append_javascript (main.min.js?v=7af39fe9ec3585e958e8637ace5e96fe0bf3ced51a8b8b5875c571f941299779fe746bf74f02bab0f3c6e08281d6ecadafcb5b08120e98f081c9c7dd824bdfdc:35619), <anonymous>:228:27)
    at Object.main.register_plugin (eval at append_javascript (main.min.js?v=7af39fe9ec3585e958e8637ace5e96fe0bf3ced51a8b8b5875c571f941299779fe746bf74f02bab0f3c6e08281d6ecadafcb5b08120e98f081c9c7dd824bdfdc:35619), <anonymous>:268:24)
    at eval (eval at append_javascript (main.min.js?v=7af39fe9ec3585e958e8637ace5e96fe0bf3ced51a8b8b5875c571f941299779fe746bf74f02bab0f3c6e08281d6ecadafcb5b08120e98f081c9c7dd824bdfdc:35619), <anonymous>:1026:26)
    at eval (eval at append_javascript (main.min.js?v=7af39fe9ec3585e958e8637ace5e96fe0bf3ced51a8b8b5875c571f941299779fe746bf74f02bab0f3c6e08281d6ecadafcb5b08120e98f081c9c7dd824bdfdc:35619), <anonymous>:1031:7)
VM32:19 Bokeh: ERROR: Unable to run BokehJS code because BokehJS library is missing
DevTools failed to load SourceMap: Could not load content for http://localhost:8890/static/notebook/js/main.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
```

<img width="1161" alt="Screenshot 2021-03-30 at 14 15 36" src="https://user-images.githubusercontent.com/7266636/112994730-73c45000-9162-11eb-99f0-18a0ba3bd441.png">

**Comment by Sidney-Bishop** [comment]
For comparision I've performed a fresh install of anaconda on Windows ( via Parallels on my MAC ).

I run conda update --all

Then when running these tow lines of code only:

```
import holoviews as hv
hv.extension('bokeh')
```

I get this error:

```
Javascript error adding output!
Error: Cannot find module '@bokehjs/styles/buttons'
See your browser Javascript console for more details.
```

!bokeh info gives:

```
Python version      :  3.8.8 (default, Feb 24 2021, 15:54:32) [MSC v.1928 64 bit (AMD64)]
IPython version     :  7.21.0
Tornado version     :  6.1
Bokeh version       :  2.3.0
BokehJS static path :  C:\Users\user1\anaconda3\lib\site-packages\bokeh\server\static
node.js version     :  (not installed)
npm version         :  (not installed)
```

**Comment by ahuang11** [comment]
It's not rendering for jupyter notebook either:

```
import panel
import holoviews as hv
hv.__version__
import hvplot.xarray
panel.__version__
import bokeh
bokeh.__version__

import xarray as xr
ds = xr.tutorial.open_dataset('air_temperature')
ds.hvplot('time')
```
```
'1.14.2'
'0.11.1'
'2.3.0'
```

**Comment by philippjfr** [comment]
@mattpap any ideas what the "Cannot find module @bokeh/styles/buttons" error might be about?

**Comment by mattpap** [comment]
> any ideas what the "Cannot find module `@bokeh/styles/buttons`" error might be about?

This seems to be a version mismatch. This module was present in bokehjs 2.2, but was replaced in 2.3 (PR #10732).

**Comment by McAldo** [comment]
I am experiencing a similar problem.
![image](https://user-images.githubusercontent.com/6762537/113455365-54e3e900-9402-11eb-8a7b-15d86f7f3ecc.png)

![image](https://user-images.githubusercontent.com/6762537/113455330-40075580-9402-11eb-9ac0-de85c7c75a3f.png)

This happens both in chrome and Firefox.
I am running the latest version of Anaconda. Chrome Javascript console reports:
![image](https://user-images.githubusercontent.com/6762537/113455643-126edc00-9403-11eb-8132-fc324dcd3543.png)

**Comment by philippjfr** [comment]
Could everyone try to install latest panel (>0.11) from the pyviz channel?

**Comment by Sidney-Bishop** [comment]
@philippjfr many thanks for your help.
I've installed panel-0.9.7 ( see below ) and now my jupyter notebook plot works. 

<img width="1161" alt="Screenshot 2021-04-03 at 11 27 06" src="https://user-images.githubusercontent.com/7266636/113475819-92cb2680-946f-11eb-951e-3d6420361fc5.png">


`conda install -c anaconda panel
Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /Users/jasonroche/opt/anaconda3

  added / updated specs:
    - panel


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    ca-certificates-2020.10.14 |                0         127 KB  anaconda
    certifi-2020.6.20          |           py38_0         159 KB  anaconda
    panel-0.9.7                |             py_0         909 KB  anaconda
    ------------------------------------------------------------
                                           Total:         1.2 MB

The following packages will be SUPERSEDED by a higher-priority channel:

  ca-certificates    conda-forge::ca-certificates-2020.12.~ --> anaconda::ca-certificates-2020.10.14-0
  certifi            conda-forge::certifi-2020.12.5-py38h5~ --> anaconda::certifi-2020.6.20-py38_0
  panel                pkgs/main::panel-0.10.3-pyhd3eb1b0_1 --> anaconda::panel-0.9.7-py_0`

**Comment by philippjfr** [comment]
Panel 0.9.7 is very old, I was more hoping you'd upgrade to Panel 0.11.1 using `conda install -c pyviz panel`. Glad it's working for you though.

**Comment by Sidney-Bishop** [comment]
Ok great thanks,

I upgraded to panel-0.11.1  and it works. 

**However**, i had to clear the notebook, restart the jupyter server ( because the old error persisted for two executions ).

`conda install -c pyviz panel
Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /Users/jasonroche/opt/anaconda3

  added / updated specs:
    - panel


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    panel-0.11.1               |             py_0         6.6 MB  pyviz
    ------------------------------------------------------------
                                           Total:         6.6 MB

The following packages will be UPDATED:

  ca-certificates    anaconda::ca-certificates-2020.10.14-0 --> pkgs/main::ca-certificates-2021.1.19-hecd8cb5_1
  certifi                anaconda::certifi-2020.6.20-py38_0 --> pkgs/main::certifi-2020.12.5-py38hecd8cb5_0
  panel                          anaconda::panel-0.9.7-py_0 --> pyviz::panel-0.11.1-py_0

`

**Comment by McAldo** [comment]
@philippjfr Thanks for your advice.
I run
conda install -c pyviz panel
Which installed with no errors.

However, Jupyter seems now unable to launch.
It displays a pagesaying:
This page should redirect you to Jupyter Notebook. If it doesn't, click here to go to Jupyter. 

The link is:http://localhost:8888/tree?token=aac0b6c6701f65de081ffb6dbbd8c9ee383b316b6e60a413
But it will not open.

Jupyter reports the following errors:

```
[I 19:14:47.262 NotebookApp] The port 8888 is already in use, trying another port.
[I 19:14:47.264 NotebookApp] The port 8889 is already in use, trying another port.
[I 19:14:47.264 NotebookApp] The port 8890 is already in use, trying another port.
[W 19:14:47.264 NotebookApp] Error loading server extension jupyter_nbextensions_configurator
    Traceback (most recent call last):
      File "C:\Users\sudoa\anaconda3\lib\site-packages\notebook\notebookapp.py", line 2033, in init_server_extensions
        mod = importlib.import_module(modulename)
      File "C:\Users\sudoa\anaconda3\lib\importlib\__init__.py", line 127, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
      File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
      File "<frozen importlib._bootstrap>", line 991, in _find_and_load
      File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
    ModuleNotFoundError: No module named 'jupyter_nbextensions_configurator'
[W 2021-04-03 19:14:48.420 LabApp] 'notebook_dir' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[W 2021-04-03 19:14:48.420 LabApp] 'notebook_dir' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[I 2021-04-03 19:14:48.430 LabApp] JupyterLab extension loaded from C:\Users\sudoa\anaconda3\lib\site-packages\jupyterlab
[I 2021-04-03 19:14:48.438 LabApp] JupyterLab application directory is C:\Users\sudoa\anaconda3\share\jupyter\lab
[I 19:14:49.539 NotebookApp] Serving notebooks from local directory: C:\Users\sudoa
[I 19:14:49.539 NotebookApp] Jupyter Notebook 6.3.0 is running at:
[I 19:14:49.539 NotebookApp] http://localhost:8891/?token=643e335319d8cb1407813e81c9835307a2154b68a9606a98
[I 19:14:49.547 NotebookApp]  or http://127.0.0.1:8891/?token=643e335319d8cb1407813e81c9835307a2154b68a9606a98
[I 19:14:49.547 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 19:14:49.590 NotebookApp]

    To access the notebook, open this file in a browser:
        file:///C:/Users/sudoa/AppData/Roaming/jupyter/runtime/nbserver-74176-open.html
    Or copy and paste one of these URLs:
        http://localhost:8891/?token=643e335319d8cb1407813e81c9835307a2154b68a9606a98
     or http://127.0.0.1:8891/?token=643e335319d8cb1407813e81c9835307a2154b68a9606a98

```

This might be something very trivial I am missing though.
Unfortunately I am very unfamiliar with both Anaconda and Jupyter, hayving started fiddling with it just yesterday.
Perhaps there are more components which I should update in order for everything to work?
Thanks!

**Comment by philippjfr** [comment]
The server you launched says it's running on port 8891 but your link is pointing to port 8888. Make sure to follow the link that is printed in the terminal.

**Comment by McAldo** [comment]
> 
> 
> The server you launched says it's running on port 8891 but your link is pointing to port 8888. Make sure to follow the link that is printed in the terminal.

Thanks,
I tried several times, using each time the links in the terminal as suggested.
But this does not load Jupyter, the page seems stuck on loading.

This was the last execution ouput:
I tried on chrome and firefox both:
_http://127.0.0.1:8889/?token=7f563a3066c853f4a98859d5e1ee9d876b13115e58475d13_
and
_http://localhost:8889/?token=7f563a3066c853f4a98859d5e1ee9d876b13115e58475d13_

But no luck they will not load.
If I press CTRL-C as suggested in the terminal, the terminal will close and the server will stop and the browser will display an Unable To Connect page.

`[I 19:42:31.654 NotebookApp] The port 8888 is already in use, trying another port.
[W 19:42:31.661 NotebookApp] Error loading server extension jupyter_nbextensions_configurator
    Traceback (most recent call last):
      File "C:\Users\sudoa\anaconda3\lib\site-packages\notebook\notebookapp.py", line 2033, in init_server_extensions
        mod = importlib.import_module(modulename)
      File "C:\Users\sudoa\anaconda3\lib\importlib\__init__.py", line 127, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
      File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
      File "<frozen importlib._bootstrap>", line 991, in _find_and_load
      File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
    ModuleNotFoundError: No module named 'jupyter_nbextensions_configurator'
[W 2021-04-03 19:42:32.910 LabApp] 'notebook_dir' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[W 2021-04-03 19:42:32.910 LabApp] 'notebook_dir' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[I 2021-04-03 19:42:32.926 LabApp] JupyterLab extension loaded from C:\Users\sudoa\anaconda3\lib\site-packages\jupyterlab
[I 2021-04-03 19:42:32.926 LabApp] JupyterLab application directory is C:\Users\sudoa\anaconda3\share\jupyter\lab
[I 19:42:34.115 NotebookApp] Serving notebooks from local directory: C:\Users\sudoa
[I 19:42:34.115 NotebookApp] Jupyter Notebook 6.3.0 is running at:
[I 19:42:34.115 NotebookApp] http://localhost:8889/?token=7f563a3066c853f4a98859d5e1ee9d876b13115e58475d13
[I 19:42:34.115 NotebookApp]  or http://127.0.0.1:8889/?token=7f563a3066c853f4a98859d5e1ee9d876b13115e58475d13
[I 19:42:34.115 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 19:42:34.168 NotebookApp]

    To access the notebook, open this file in a browser:
        file:///C:/Users/sudoa/AppData/Roaming/jupyter/runtime/nbserver-33284-open.html
    Or copy and paste one of these URLs:
        http://localhost:8889/?token=7f563a3066c853f4a98859d5e1ee9d876b13115e58475d13
     or http://127.0.0.1:8889/?token=7f563a3066c853f4a98859d5e1ee9d876b13115e58475d13`

**Comment by McAldo** [comment]
So, I tried and create a new environment, which brought back Jupyter to life.
Then I downgraded panel to 
![image](https://user-images.githubusercontent.com/6762537/113489556-d5672000-94bc-11eb-99a6-521a42a8b2f5.png)

directly from conda.
HvPlot now runs fine:
![image](https://user-images.githubusercontent.com/6762537/113489593-00517400-94bd-11eb-9832-9c53a2c2a5fa.png)

Not an ideal solution of course, but at least for the moment I can keep fiddling and learning.

Thanks for the help!

**Comment by Sidney-Bishop** [comment]
> So, I tried and create a new environment, which brought back Jupyter to life.
> Then I downgraded panel to
> ![image](https://user-images.githubusercontent.com/6762537/113489556-d5672000-94bc-11eb-99a6-521a42a8b2f5.png)
> 
> directly from conda.
> HvPlot now runs fine:
> ![image](https://user-images.githubusercontent.com/6762537/113489593-00517400-94bd-11eb-9832-9c53a2c2a5fa.png)
> 
> Not an ideal solution of course, but at least for the moment I can keep fiddling and learning.
> 
> Thanks for the help!

@McAldo did you get sorted out in the end? Usually killing an existing server instance with CTRL-C  fixes port conflicts with a new one. Stick with it !! Holoviews is a power mechanism to realise a [Literate-Programming_Paradigm](https://www.researchgate.net/publication/2954036_The_Literate-Programming_Paradigm/link/544e64e20cf26dda08900f8c/download) where you can close the traditional "chasm" between technical developers and business decision makers by reducing the technical barriers to entry to enterprise problems by exposing data through intuitive interactive graphical interfaces facilitating:

- realtime time business decisions 
- reproducibility 
- extensibility
- transparency

**Comment by Dr-Irv** [comment]
> Could everyone try to install latest panel (>0.11) from the pyviz channel?

I tried that and now I get graphics, but it seems that the notebook magic for cell width/height is being ignored.  See pic, where I took the example from https://holoviews.org/user_guide/Notebook_Magics.html

![image](https://user-images.githubusercontent.com/15113894/113511358-6b3a9380-952d-11eb-871a-ac7921ffdf00.png)

**Comment by Sidney-Bishop** [comment]
> > Could everyone try to install latest panel (>0.11) from the pyviz channel?
> 
> I tried that and now I get graphics, but it seems that the notebook magic for cell width/height is being ignored. See pic, where I took the example from https://holoviews.org/user_guide/Notebook_Magics.html
> 
> ![image](https://user-images.githubusercontent.com/15113894/113511358-6b3a9380-952d-11eb-871a-ac7921ffdf00.png)

@Dr-Irv  that code seems to run ok for me ( see below )

<img width="1035" alt="Screenshot 2021-04-04 at 16 03 11" src="https://user-images.githubusercontent.com/7266636/113513015-6262b580-955f-11eb-95dd-ee6a22a5b1f3.png">

panel-0.11.1  

`Python version      :  3.8.8 (default, Feb 24 2021, 13:46:16) 
IPython version     :  7.21.0
Tornado version     :  6.1
Bokeh version       :  2.3.0
BokehJS static path :  /Users/jasonroche/opt/anaconda3/lib/python3.8/site-packages/bokeh/server/static
node.js version     :  (not installed)
npm version         :  (not installed)`

**Comment by Dr-Irv** [comment]
@sidney-bishop I have the same versions, but I'm on Windows.

**Comment by Sidney-Bishop** [comment]
> @Sidney-Bishop I have the same versions, but I'm on Windows.

@Dr-Irv  ok I will try it on windows and see what happens. I run windows 10 through parallels VM

**Comment by Dr-Irv** [comment]
I saw on gitter the following, and it seems to solve the problem:
```
conda update --all -c pyviz -c conda-forge
```

So I guess the versions in the main conda channel are no longer working.

**Comment by philippjfr** [comment]
Panel has just not been updated on the conda defaults channel yet, should happen very soon though.

**Comment by Dr-Irv** [comment]
It wasn’t enough for me to just update panel. Doing a full update from the
pyviz channel was necessary. Not sure what other package needs the update.

Sent from my iPhone

On Apr 4, 2021, at 1:31 PM, Philipp Rudiger ***@***.***>
wrote:

﻿

Panel has just not been updated on the conda defaults channel yet, should
happen very soon though.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/holoviz/holoviews/issues/4875#issuecomment-813069871>,
or unsubscribe

**Comment by McAldo** [comment]
> 
> @McAldo did you get sorted out in the end? Usually killing an existing server instance with CTRL-C fixes port conflicts with a new one. Stick with it !! Holoviews is a power mechanism to realise a [Literate-Programming_Paradigm](https://www.researchgate.net/publication/2954036_The_Literate-Programming_Paradigm/link/544e64e20cf26dda08900f8c/download) where you can close the traditional "chasm" between technical developers and business decision makers by reducing the technical barriers to entry to enterprise problems by exposing data through intuitive interactive graphical interfaces facilitating:
> 
>     * realtime time business decisions
> 
>     * reproducibility
> 
>     * extensibility
> 
>     * transparency

Thanks, I am loving Holoviews. In particular, Responsive graphs are really useful for so many things.
Regarding stopping the server via CTRL-C to free the 8888 port, I tried but I was unable to.
Essentially, upon launching Jupyter there seemed to be one or more servers already running every time.
CTRL-C in terminal would close the Jupyter server linked to that terminal, but not the one using port 8888.
There is no terminal window open for that one. At least, not that I can see (but I am just starting with python and anaconda, so probably there are very obvious solutions which I am unaware of).
I am on Windows 10, I checked the PID of the application using port 8888, and it was a python process.
I even tried killing that process from task manager and running Jupyter again, but as soon as I did so, there were again two servers running rather than only one and Jupyter would not load.
When downgrading to Panel 0.97, the problem went away. Only one server is created upon launching Jupyter and the code runs without conflicts in Firefox and Chrome both.

I am aware that running Panel 0.97 is not ideal, quite a lot of features have been added afterwards. I guess I will try and upgrade soon.

**Comment by Dr-Irv** [comment]
So now it seems that updating just `panel` from `pyviz` does the trick.  The following sequence worked:
```
conda create -n hvtest0405 python=3.8
conda activate hvtest0405
conda install pandas holoviews jupyter
conda install panel -c pyviz
```

**Comment by philippjfr** [comment]
Thanks @Dr-Irv that should indeed be sufficient and even that won't be needed once we get Panel 0.11+ on conda defaults which should happen in the next couple of days.

**Comment by MikeB2019x** [comment]
I'm not sure but following the `panel` update advice seems to have cleared up problems I was having in `issue #4861`.  Could be a coincidence?

**Comment by jbhiatt** [comment]
I am having the same problem. I set up a fresh conda environment including the latest versions of panel, jupyter lab, bokeh, etc, but I am still unable to overcome this issue. Versions are listed below. Please help! Thank you!!

Code:
```
import holoviews as hv
import numpy as np
hv.extension('bokeh')
xs = [0.1* i for i in range(100)]
curve =  hv.Curve((xs, [np.sin(x) for x in xs]))
scatter =  hv.Scatter((xs[::5], np.linspace(0,1,20)))
curve + scatter
```

Result:
blank cell

Error message (in browser console): 
`Uncaught Error: Cannot find module '@bokehjs/styles/buttons'`

Package versions:
```
panel                     0.11.3                     py_0    pyviz
jupyter                   1.0.0            py38h578d9bd_6    conda-forge
jupyter-packaging         0.9.1              pyhd8ed1ab_0    conda-forge
jupyter_bokeh             3.0.0              pyhd8ed1ab_0    conda-forge
jupyter_client            6.1.12             pyhd8ed1ab_0    conda-forge
jupyter_console           6.4.0              pyhd8ed1ab_0    conda-forge
jupyter_core              4.7.1            py38h578d9bd_0    conda-forge
jupyter_server            1.6.1            py38h578d9bd_0    conda-forge
jupyterlab                3.0.14             pyhd8ed1ab_0    conda-forge
jupyterlab_pygments       0.1.2              pyh9f0ad1d_0    conda-forge
jupyterlab_server         2.4.0              pyhd8ed1ab_0    conda-forge
jupyterlab_widgets        1.0.0              pyhd8ed1ab_1    conda-forge
bokeh                     2.3.1            py38h578d9bd_0    conda-forge
jupyter_bokeh             3.0.0              pyhd8ed1ab_0    conda-forge
holoviews                 1.14.3                     py_0    pyviz
pyviz_comms               2.0.1                      py_0    pyviz
ipython                   7.22.0           py38hd0cf306_0    conda-forge
python                    3.8.8           hffdb5ce_0_cpython    conda-forge
```

Joe

**Comment by philippjfr** [comment]
Since there has been no activity here for a while and it is generally working I'm going to close. If you encounter this again please open a new issue.

**Comment by basnijholt** [comment]
I have just created a fresh environment without pinning any versions, which then results in:
```
name: adaptive-docs

channels:
  - conda-forge

dependencies:
  - python=3.11.3
  - sortedcollections=2.1.0
  - scikit-optimize=0.9.0
  - scikit-learn=1.2.2
  - scipy=1.10.1
  - holoviews=1.15.4
  - bokeh=2.4.3
  - panel=0.14.4
  - pandas=2.0.0
  - plotly=5.14.1
  - ipywidgets=8.0.6
  - myst-nb=0.17.1
  - sphinx_fontawesome=0.0.6
  - sphinx=5.3.0
  - ffmpeg=5.1.2
  - cloudpickle=2.2.1
  - loky=3.3.0
  - furo=2023.3.27
  - myst-parser=0.18.1
  - dask=2023.3.2
```

I am still getting this error in Jupyter notebook classic.
