### ISSUE TITLE
Build workflow failing on pypi probably due to `nbconvert`

### ISSUE THREAD

**Issue by maximlt** [holoviz/holoviews#5167]
In the process of releasing version `1.14.7` I've seen the unit tests suite failing on the build/pypi workflow with the following error (4 failing tests, same error):
```
======================================================================
ERROR: test_opts_image_line_magic_svg (holoviews.tests.ipython.testnotebooks.TestOptsPreprocessor)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/share/miniconda3/envs/test-environment/lib/python3.7/site-packages/traitlets/traitlets.py", line 537, in get
    value = obj._trait_values[self.name]
KeyError: 'template_paths'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/holoviews/holoviews/.tox/py37-unit-default-pkg/lib/python3.7/site-packages/holoviews/tests/ipython/testnotebooks.py", line 64, in test_opts_image_line_magic_svg
    source = apply_preprocessors([OutputMagicProcessor()], nbname)
  File "/home/runner/work/holoviews/holoviews/.tox/py37-unit-default-pkg/lib/python3.7/site-packages/holoviews/tests/ipython/testnotebooks.py", line 16, in apply_preprocessors
    exporter = nbconvert.PythonExporter()
  File "/usr/share/miniconda3/envs/test-environment/lib/python3.7/site-packages/nbconvert/exporters/templateexporter.py", line 330, in __init__
    super().__init__(config=config, **kw)
  File "/usr/share/miniconda3/envs/test-environment/lib/python3.7/site-packages/nbconvert/exporters/exporter.py", line 114, in __init__
    self._init_preprocessors()
  File "/usr/share/miniconda3/envs/test-environment/lib/python3.7/site-packages/nbconvert/exporters/templateexporter.py", line 497, in _init_preprocessors
    conf = self._get_conf()
  File "/usr/share/miniconda3/envs/test-environment/lib/python3.7/site-packages/nbconvert/exporters/templateexporter.py", line 515, in _get_conf
    for path in map(Path, self.template_paths):
  File "/usr/share/miniconda3/envs/test-environment/lib/python3.7/site-packages/traitlets/traitlets.py", line 577, in __get__
    return self.get(obj, cls)
  File "/usr/share/miniconda3/envs/test-environment/lib/python3.7/site-packages/traitlets/traitlets.py", line 540, in get
    default = obj.trait_defaults(self.name)
  File "/usr/share/miniconda3/envs/test-environment/lib/python3.7/site-packages/traitlets/traitlets.py", line 1580, in trait_defaults
    return self._get_trait_default_generator(names[0])(self)
  File "/usr/share/miniconda3/envs/test-environment/lib/python3.7/site-packages/traitlets/traitlets.py", line 977, in __call__
    return self.func(*args, **kwargs)
  File "/usr/share/miniconda3/envs/test-environment/lib/python3.7/site-packages/nbconvert/exporters/templateexporter.py", line 526, in _template_paths
    template_names = self.get_template_names()
  File "/usr/share/miniconda3/envs/test-environment/lib/python3.7/site-packages/nbconvert/exporters/templateexporter.py", line 609, in get_template_names
    raise ValueError('No template sub-directory with name %r found in the following paths:\n\t%s' % (base_template, paths))
ValueError: No template sub-directory with name 'python' found in the following paths:
	/home/runner/.local/share/jupyter
	/home/runner/work/holoviews/holoviews/.tox/py37-unit-default-pkg/share/jupyter
	/usr/local/share/jupyter
	/usr/share/jupyter
```

Packages of interest in the env to try to reproduce:
```
jupyter_client-7.0.6 
jupyter_core-4.9.1
nbclient-0.5.3
nbconvert-6.1.0
nbformat-5.1.3
notebook-6.4.6
```

See the logs of the failing action [here](https://github.com/holoviz/holoviews/runs/4544995447?check_suite_focus=true)

Note that we've recently had to update `nbsmoke` to add compatibility with `nbconvert>6` (see https://github.com/pyviz-dev/nbsmoke/pull/57/). The errors reported in this issue are unrelated to `nbsmoke` but the change made in this PR can guide the changes required (if there really are changes needed) in holoviews.

To release version `1.14.7.` I've pinned `nbconvert<6` in the build/pypi workflow (https://github.com/holoviz/holoviews/pull/5134/commits/8d829c40c69ee0f0e07b6175b618e164f78e6f8e).

TODOs

- [x] Cherry pick https://github.com/holoviz/holoviews/pull/5134/commits/8d829c40c69ee0f0e07b6175b618e164f78e6f8e to `master`
- [x] Add a `doit env_capture` step in the build workflow before the test suite runs
- [ ] Reproduce the bug

**Comment by maximlt** [comment]
I've not tried to reproduce the bug since pinning nbconvert was enough to fix it.
