### ISSUE TITLE
Can't Import Holoviews

### ISSUE THREAD

**Issue by BrandonSLockey** [holoviz/holoviews#5244]
#### ALL software version info
(this library, plus any other relevant software, e.g. bokeh, python, notebook, OS, browser, etc)

#### Description of expected behavior and the observed behavior
Im trying to install holoviews for UMAP

#### Complete, minimal, self-contained example code that reproduces the issue

```
import holoviews as hv

```

#### Stack traceback and/or browser JavaScript console output
import holoviews as hv
Traceback (most recent call last):

  File "C:\Users\brand\AppData\Local\Temp/ipykernel_1540/4081495914.py", line 1, in <module>
    import holoviews as hv

  File "C:\Users\brand\anaconda3\envs\SALIB\lib\site-packages\holoviews\__init__.py", line 12, in <module>
    from .annotators import annotate                         # noqa (API import)

  File "C:\Users\brand\anaconda3\envs\SALIB\lib\site-packages\holoviews\annotators.py", line 10, in <module>
    from panel.pane import PaneBase

  File "C:\Users\brand\anaconda3\envs\SALIB\lib\site-packages\panel\__init__.py", line 1, in <module>
    from . import layout # noqa

  File "C:\Users\brand\anaconda3\envs\SALIB\lib\site-packages\panel\layout\__init__.py", line 1, in <module>
    from .accordion import Accordion # noqa

  File "C:\Users\brand\anaconda3\envs\SALIB\lib\site-packages\panel\layout\accordion.py", line 5, in <module>
    from .base import NamedListPanel

  File "C:\Users\brand\anaconda3\envs\SALIB\lib\site-packages\panel\layout\base.py", line 13, in <module>
    from ..reactive import Reactive

  File "C:\Users\brand\anaconda3\envs\SALIB\lib\site-packages\panel\reactive.py", line 26, in <module>
    from .config import config

  File "C:\Users\brand\anaconda3\envs\SALIB\lib\site-packages\panel\config.py", line 21, in <module>
    from .io.notebook import load_notebook

  File "C:\Users\brand\anaconda3\envs\SALIB\lib\site-packages\panel\io\__init__.py", line 9, in <module>
    from ..config import config

ImportError: cannot import name 'config' from partially initialized module 'panel.config' (most likely due to a circular import) (C:\Users\brand\anaconda3\envs\SALIB\lib\site-packages\panel\config.py)

#### Screenshots or screencasts of the bug in action

cannot import name 'config' from partially initialized module 'panel.config' (most likely due to a circular import)

![image](https://user-images.githubusercontent.com/72495991/159951276-763629dc-2dd9-4bcd-a79c-39d6421daa82.png)

**Comment by MichaelGiazi** [comment]
I have a similar (?) issue trying to import the package from PyPI:

```>>> import holoviews
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/mg/.local/share/virtualenvs/hvTest-xxMFZooO/lib/python3.9/site-packages/holoviews/__init__.py", line 12, in <module>
    from .annotators import annotate                         # noqa (API import)
  File "/home/mg/.local/share/virtualenvs/hvTest-xxMFZooO/lib/python3.9/site-packages/holoviews/annotators.py", line 10, in <module>
    from panel.pane import PaneBase
  File "/home/mg/.local/share/virtualenvs/hvTest-xxMFZooO/lib/python3.9/site-packages/panel/__init__.py", line 1, in <module>
    from . import layout # noqa
  File "/home/mg/.local/share/virtualenvs/hvTest-xxMFZooO/lib/python3.9/site-packages/panel/layout/__init__.py", line 1, in <module>
    from .accordion import Accordion # noqa
  File "/home/mg/.local/share/virtualenvs/hvTest-xxMFZooO/lib/python3.9/site-packages/panel/layout/accordion.py", line 5, in <module>
    from .base import NamedListPanel
  File "/home/mg/.local/share/virtualenvs/hvTest-xxMFZooO/lib/python3.9/site-packages/panel/layout/base.py", line 11, in <module>
    from ..io.model import hold
  File "/home/mg/.local/share/virtualenvs/hvTest-xxMFZooO/lib/python3.9/site-packages/panel/io/__init__.py", line 9, in <module>
    from ..config import config
  File "/home/mg/.local/share/virtualenvs/hvTest-xxMFZooO/lib/python3.9/site-packages/panel/config.py", line 21, in <module>
    from .io.notebook import load_notebook
  File "/home/mg/.local/share/virtualenvs/hvTest-xxMFZooO/lib/python3.9/site-packages/panel/io/notebook.py", line 39, in <module>
    from .resources import Bundle, Resources, _env, bundle_resources
  File "/home/mg/.local/share/virtualenvs/hvTest-xxMFZooO/lib/python3.9/site-packages/panel/io/resources.py", line 24, in <module>
    from jinja2 import Environment, Markup, FileSystemLoader
ImportError: cannot import name 'Markup' from 'jinja2' (/home/mg/.local/share/virtualenvs/hvTest-xxMFZooO/lib/python3.9/site-packages/jinja2/__init__.py)
```

**Comment by philippjfr** [comment]
Thanks you two!

@BrandonSLockey Could you report panel and holoviews versions?

@MichaelGiazi How did you install holoviews? Can you install jinja2?

**Comment by MichaelGiazi** [comment]
@philippjfr 

I simply used this Pipfile with pipenv and python 3.9:

```
[[source]]
name = "pypi"
url = "https://pypi.org/simple"
verify_ssl = true

[packages]
holoviews = "1.14.8"

```

Then just ran:

```
pipenv shell
python
>>>import holoviews
```

I also tried these versions: `1.14.7, 1.14.6, 1.14.5, 1.13.7` and got the same error

**Comment by MichaelGiazi** [comment]
@philippjfr 

Yes, it was jinja2, this fails:

```
[[source]]
name = "pypi"
url = "https://pypi.org/simple"
verify_ssl = true

[packages]
jinja2 = "==3.1.0"
holoviews = "==1.14.8"
```

but using `jinja2 = "==3.0.2"` worked correctly. Jinja2 was updated yesterday evening turns out.

**Comment by wimiko** [comment]
from the Jinja2 3.1.0 releasenotes:

> Markup and escape should be imported from MarkupSafe.

Seems that markup is not provided by jinja2 anymore and should be imported from markupsafe:

> from markupsafe import Markup

**Comment by philippjfr** [comment]
Fixed in https://github.com/holoviz/panel/pull/3258. There's now also a 0.13.0a46 dev release available with the fix. Hope to have a real release out very soon.

**Comment by philippjfr** [comment]
Panel 0.12.7 is now available on PyPI and from the conda pyviz and conda-forge channels.
