### ISSUE TITLE
Datashader throws exception when Buffer is cleared

### ISSUE THREAD

**Issue by pepijndevos** [holoviz/holoviews#5255]
#### ALL software version info
<details><summary>version info</summary>
<pre>
$ pip freeze
aiocouch==2.2.1
aiohttp==3.8.1
aiosignal==1.2.0
anyio==3.5.0
argon2-cffi==21.3.0
argon2-cffi-bindings==21.2.0
async-timeout==4.0.2
attrs==21.4.0
Babel==2.9.1
backcall==0.2.0
bleach==4.1.0
bokeh==2.4.2
certifi==2021.10.8
cffi==1.15.0
chardet==4.0.0
charset-normalizer==2.0.10
chevron==0.14.0
click==8.0.4
cloudpickle==2.0.0
colorcet==3.0.0
dask==2022.3.0
datashader==0.13.0
datashape==0.5.2
debugpy==1.5.1
decorator==5.1.1
defusedxml==0.7.1
Deprecated==1.2.13
distributed==2022.3.0
docker==5.0.3
entrypoints==0.3
escapism==1.0.1
frozenlist==1.3.0
fsspec==2022.2.0
HeapDict==1.0.1
holoviews==1.14.8
hvplot==0.7.3
ibm-cloud-sdk-core==3.13.2
ibmcloudant==0.0.41
idna==3.3
ipykernel==6.6.1
ipython==7.31.0
ipython-genutils==0.2.0
ipywidgets==7.6.5
iso8601==1.0.2
jedi==0.18.1
Jinja2==3.0.3
json5==0.9.6
jsonschema==4.4.0
jupyter-bokeh==3.0.4
jupyter-client==7.1.0
jupyter-core==4.9.1
jupyter-repo2docker==2021.8.0
jupyter-server==1.13.2
-e git+https://github.com/jupyterhub/jupyter-server-proxy.git@26d7569a7d2e7c806fcafe3b538ecbe061e7c0d8#egg=jupyter_server_proxy
jupyterlab==3.2.7
jupyterlab-pygments==0.1.2
jupyterlab-server==2.10.3
jupyterlab-widgets==1.0.2
llvmlite==0.38.0
locket==0.2.1
Markdown==3.3.6
MarkupSafe==2.0.1
matplotlib-inline==0.1.3
mistune==0.8.4
more-itertools==8.12.0
msgpack==1.0.3
multidict==6.0.2
multipledispatch==0.6.0
nbclassic==0.3.5
nbclient==0.5.9
nbconvert==6.4.0
nbformat==5.1.3
nest-asyncio==1.5.4
notebook==6.4.7
numba==0.55.1
numpy==1.21.5
packaging==21.3
pandas==1.3.5
pandocfilters==1.5.0
panel==0.12.6
param==1.12.0
parso==0.8.3
partd==1.2.0
pexpect==4.8.0
pickleshare==0.7.5
Pillow==9.0.0
plotly==5.6.0
prometheus-client==0.12.0
prompt-toolkit==3.0.24
psutil==5.9.0
ptyprocess==0.7.0
pycapnp==1.1.0
pycparser==2.21
pyct==0.4.8
Pygments==2.11.2
PyJWT==2.3.0
pyparsing==3.0.6
pyrsistent==0.18.0
python-dateutil==2.8.2
python-json-logger==2.0.2
-e git+ssh://git@github.com/NyanCAD/Pyttoresque.git@839f012e6b4061e378825aa8e039191a821c97ef#egg=Pyttoresque
pytz==2021.3
pyviz-comms==2.1.0
PyYAML==6.0
pyzmq==22.3.0
requests==2.27.1
ruamel.yaml==0.17.20
ruamel.yaml.clib==0.2.6
scipy==1.8.0
semver==2.13.0
Send2Trash==1.8.0
simpervisor==0.4
six==1.16.0
sniffio==1.2.0
sortedcontainers==2.4.0
streamz==0.6.3
tblib==1.7.0
tenacity==8.0.1
terminado==0.12.1
testpath==0.5.0
toml==0.10.2
toolz==0.11.2
tornado==6.1
tqdm==4.63.0
traitlets==5.1.1
typing_extensions==4.0.1
urllib3==1.26.8
wcwidth==0.2.5
webencodings==0.5.1
websocket-client==1.2.3
widgetsnbextension==3.5.2
wrapt==1.14.0
xarray==2022.3.0
yarl==1.7.2
zict==2.1.0
</pre>
</details>

#### Description of expected behavior and the observed behavior

When streaming data into a datashader plot, upon calling `.clear` on the underlying buffer, an error occurs.

#### Complete, minimal, self-contained example code that reproduces the issue

Setup
```
import holoviews as hv
import datashader as ds
import pandas as pd
import numpy as np
from holoviews.streams import Buffer, Stream, param
from holoviews.operation.datashader import datashade, shade, dynspread, spread, rasterize

hv.extension('plotly')

active_traces = Stream.define('traces', cols=[])

def _timeplot(data, cols=[]):
    traces = {k: hv.Curve((data.index, data[k]), 'time', 'amplitude') for k in cols}
    return hv.NdOverlay(traces, kdims='k')

def timeplot(streams):
    curve_dmap = hv.DynamicMap(_timeplot, streams=streams)
    return spread(datashade(curve_dmap, aggregator=ds.count_cat('k'), streams=[hv.streams.PlotSize]))

n=100
m=1000
def stream(streamdict):
    for i in range(n):
        res = {"stuff": pd.DataFrame({'foo': np.random.rand(m), 'bar': np.random.rand(m)+0.8, 'baz': np.random.rand(m)-0.8}, index=np.arange(m)+m*i)}
        for k, v in res.items():
            #print(list(v.columns), list(streamdict[k].data.columns))
            if k in streamdict and list(v.columns) == list(streamdict[k].data.columns):
                streamdict[k].send(v)
            else:
                buf = Buffer(v, length=int(1e9), index=False)
                streamdict[k] = buf
        # yield

cols = active_traces(cols=['foo', 'bar', 'baz'])
d = {}
stream(d)
```
Now render the plot
```
timeplot([d['stuff'], cols])
```
An clear the data
```
d['stuff'].clear()
```

Note that without `streams=[hv.streams.PlotSize]` the error does not occur until the plot is rerendered, see #5253 

#### Stack traceback and/or browser JavaScript console output
```
Traceback (most recent call last):
  File "/home/pepijn/code/asic/pyttoresque/env/lib/python3.10/site-packages/holoviews/plotting/util.py", line 277, in get_plot_frame
    return map_obj[key]
  File "/home/pepijn/code/asic/pyttoresque/env/lib/python3.10/site-packages/holoviews/core/spaces.py", line 1344, in __getitem__
    val = self._execute_callback(*tuple_key)
  File "/home/pepijn/code/asic/pyttoresque/env/lib/python3.10/site-packages/holoviews/core/spaces.py", line 1111, in _execute_callback
    retval = self.callback(*args, **kwargs)
  File "/home/pepijn/code/asic/pyttoresque/env/lib/python3.10/site-packages/holoviews/core/spaces.py", line 677, in __call__
    if not args and not kwargs and not any(kwarg_hash): return self.callable()
  File "/home/pepijn/code/asic/pyttoresque/env/lib/python3.10/site-packages/holoviews/util/__init__.py", line 1043, in dynamic_operation
    key, obj = resolve(key, kwargs)
  File "/home/pepijn/code/asic/pyttoresque/env/lib/python3.10/site-packages/holoviews/util/__init__.py", line 1032, in resolve
    return key, map_obj[key]
  File "/home/pepijn/code/asic/pyttoresque/env/lib/python3.10/site-packages/holoviews/core/spaces.py", line 1344, in __getitem__
    val = self._execute_callback(*tuple_key)
  File "/home/pepijn/code/asic/pyttoresque/env/lib/python3.10/site-packages/holoviews/core/spaces.py", line 1111, in _execute_callback
    retval = self.callback(*args, **kwargs)
  File "/home/pepijn/code/asic/pyttoresque/env/lib/python3.10/site-packages/holoviews/core/spaces.py", line 708, in __call__
    ret = self.callable(*args, **kwargs)
  File "/home/pepijn/code/asic/pyttoresque/env/lib/python3.10/site-packages/holoviews/util/__init__.py", line 1044, in dynamic_operation
    return apply(obj, *key, **kwargs)
  File "/home/pepijn/code/asic/pyttoresque/env/lib/python3.10/site-packages/holoviews/util/__init__.py", line 1036, in apply
    processed = self._process(element, key, kwargs)
  File "/home/pepijn/code/asic/pyttoresque/env/lib/python3.10/site-packages/holoviews/util/__init__.py", line 1018, in _process
    return self.p.operation.process_element(element, key, **kwargs)
  File "/home/pepijn/code/asic/pyttoresque/env/lib/python3.10/site-packages/holoviews/core/operation.py", line 194, in process_element
    return self._apply(element, key)
  File "/home/pepijn/code/asic/pyttoresque/env/lib/python3.10/site-packages/holoviews/core/operation.py", line 141, in _apply
    ret = self._process(element, key)
  File "/home/pepijn/code/asic/pyttoresque/env/lib/python3.10/site-packages/holoviews/operation/datashader.py", line 1535, in _process
    agg = rasterize._process(self, element, key)
  File "/home/pepijn/code/asic/pyttoresque/env/lib/python3.10/site-packages/holoviews/operation/datashader.py", line 1514, in _process
    element = element.map(op, predicate)
  File "/home/pepijn/code/asic/pyttoresque/env/lib/python3.10/site-packages/holoviews/core/dimension.py", line 707, in map
    if applies: deep_mapped = map_fn(deep_mapped)
  File "/home/pepijn/code/asic/pyttoresque/env/lib/python3.10/site-packages/holoviews/core/operation.py", line 214, in __call__
    return self._apply(element)
  File "/home/pepijn/code/asic/pyttoresque/env/lib/python3.10/site-packages/holoviews/core/operation.py", line 141, in _apply
    ret = self._process(element, key)
  File "/home/pepijn/code/asic/pyttoresque/env/lib/python3.10/site-packages/holoviews/operation/datashader.py", line 449, in _process
    return overlay_aggregate(element, **params)
  File "/home/pepijn/code/asic/pyttoresque/env/lib/python3.10/site-packages/param/parameterized.py", line 3631, in __new__
    return inst.__call__(*args,**params)
  File "/home/pepijn/code/asic/pyttoresque/env/lib/python3.10/site-packages/holoviews/core/operation.py", line 214, in __call__
    return self._apply(element)
  File "/home/pepijn/code/asic/pyttoresque/env/lib/python3.10/site-packages/holoviews/core/operation.py", line 141, in _apply
    ret = self._process(element, key)
  File "/home/pepijn/code/asic/pyttoresque/env/lib/python3.10/site-packages/holoviews/operation/datashader.py", line 560, in _process
    groups.append((k, agg.clone(agg.data, bounds=bbox)))
  File "/home/pepijn/code/asic/pyttoresque/env/lib/python3.10/site-packages/holoviews/element/raster.py", line 429, in clone
    return super(Image, self).clone(data, shared_data, new_type, link,
  File "/home/pepijn/code/asic/pyttoresque/env/lib/python3.10/site-packages/holoviews/core/data/__init__.py", line 1211, in clone
    return super(Dataset, self).clone(
  File "/home/pepijn/code/asic/pyttoresque/env/lib/python3.10/site-packages/holoviews/core/dimension.py", line 576, in clone
    return clone_type(data, *args, **{k:v for k,v in settings.items()
  File "/home/pepijn/code/asic/pyttoresque/env/lib/python3.10/site-packages/holoviews/element/raster.py", line 324, in __init__
    xdensity = xdensity if xdensity else util.compute_density(l, r, dim1, self._time_unit)
  File "/home/pepijn/code/asic/pyttoresque/env/lib/python3.10/site-packages/holoviews/core/util.py", line 2077, in compute_density
    return length/diff
ZeroDivisionError: float division by zero
```
#### Screenshots or screencasts of the bug in action
![image](https://user-images.githubusercontent.com/168609/161572018-a51c81fa-ad32-47dc-8ab7-172b5bb0f698.png)

**Comment by pepijndevos** [comment]
Alternate setup:
Use `aggregator=ds.by('k', ds.count())` which will instead cause `IndexError('iloc cannot enlarge its target object')`

**Comment by jbednar** [comment]
Ugh.  Looks like there are still some edge cases to handle here; rare for hand-constructed plots (who'd plot empty data?) but natural to come up in cases like this. @jlstevens , should this be handled by HoloViews, or would you rather Datashader return a tiny empty image?

**Comment by jlstevens** [comment]
I guess HoloViews could catch this and return a single transparent pixel? I'm not really sure how to think about empty images (especially due to the zero sized extents).

**Comment by pepijndevos** [comment]
This too does not actually rely on streaming, just an empty dataframe will do it. So very similar to #5256
```
import holoviews as hv
import datashader as ds
import pandas as pd
import numpy as np
from holoviews.streams import Buffer, Stream, param
from holoviews.operation.datashader import datashade, shade, dynspread, spread, rasterize

hv.extension('plotly')

n=100
m=1
i = 0
df = pd.DataFrame({'foo': [], 'bar': [], 'baz': []})


traces = {k: hv.Curve((df.index, df[k]), 'time', 'amplitude') for k in df.columns}
curves = hv.NdOverlay(traces, kdims='k')

spread(datashade(curves, aggregator=ds.count_cat('k')))
```
