### ISSUE TITLE
Exception: an unreferenced orphan tree may persist in memory

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/holoviews#5449]
hvplot=0.8.1, holoviews=1.15.0

```python
import pandas as pd

import hvplot.pandas

df = pd.DataFrame(
    {
        "actual": [100, 150, 125, 140, 145, 135, 123],
        "forecast": [90, 160, 125, 150, 141, 141, 120],
        "date": pd.date_range("2022-01-03", "2022-01-09"),
        "string": ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"],
        "numerical": [1.1, 1.9, 3.2, 3.8, 4.3, 5.0, 5.5],
    },
)
line = df.hvplot.line(
    x="numerical",
    y="actual",
)
```

```bash
$ python 'script.py'
Exception ignored in: functools.partial(<function cleanup_custom_options at 0x7f8a27075a60>, 2)
Traceback (most recent call last):
  File "/home/jovyan/conda-envs/hvplot_dev/lib/python3.9/site-packages/holoviews/core/options.py", line 80, in cleanup_custom_options
Exception: Cleanup of custom options tree with id '2' failed with the following exception: 'NoneType' object has no attribute '_options_context', an unreferenced orphan tree may persist in memory.
(/home/jovyan/conda-envs/hvplot_dev) jovyan@jupyter-masma:~/repos/private/hvplot$ python 'script.py'
Exception ignored in: functools.partial(<function cleanup_custom_options at 0x7fcca81c7a60>, 2)
Traceback (most recent call last):
  File "/home/jovyan/conda-envs/hvplot_dev/lib/python3.9/site-packages/holoviews/core/options.py", line 80, in cleanup_custom_options
Exception: Cleanup of custom options tree with id '2' failed with the following exception: 'NoneType' object has no attribute '_options_context', an unreferenced orphan tree may persist in memory.
```

**Comment by maximlt** [comment]
I've seen this error too.

**Comment by Jhsmit** [comment]
I have the same issue in a clean conda env on Windows, I ran `mamba install panel holoviz hvplot` to install dependencies, versions are:

```
  - bokeh=2.4.3=py39haa95532_0
  - holoviews=1.15.2=py39haa95532_0
  - hvplot=0.8.1=py39haa95532_0
  - panel=0.14.1=py39haa95532_0

```

**Comment by prateekdesai04** [comment]
How was this solved?

**Comment by davidM3n3ses** [comment]
i have the same message when i excute the line
points = hv.Points(base_dato, [y, y]).opts(color="crimson") , even i tried with holoview tuttorial and the result was the same. Someone have a idea ?

**Comment by koushik-ta** [comment]
I am also getting the same exception,

these are the libraries I am using:

```sh
"panel==1.6.1",
"bokeh>=3.5.0,<3.7.0",
"holoviews==1.21.0",
"hvplot==0.11.2",
```
