### ISSUE TITLE
xarray required dependency to import rasterize

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/holoviews#5523]
I'm trying to see if I can use duckdb with hvPlot/ HoloViews via ibis.

Now I'm ready to datashade/ rasterize some data following https://holoviews.org/user_guide/Large_Data.html.

When I run

```python
from holoviews.operation.datashader import rasterize
```

I get

```python
Traceback (most recent call last):
  File "C:\repos\private\hvplot\script2.py", line 1, in <module>
    from holoviews.operation.datashader import rasterize
  File "C:\repos\private\hvplot\.venv\lib\site-packages\holoviews\operation\datashader.py", line 9, in <module>
    import xarray as xr
ModuleNotFoundError: No module named 'xarray'
```

`xarray` is not a dependency of HoloViews, so I believe this is a bug.

**Comment by MarcSkovMadsen** [comment]
I can see that xarray is a requirement of datashader. So closing this one.
