### ISSUE TITLE
Intermitent error when running a module

### ISSUE THREAD

**Issue by maximlt** [holoviz/holoviews#5533]
I have observed a very strange bug. It occurs intermittently when the test suite of Panel runs, when the `doc/user_guide/APIs.md` file is being executed. I've extracted its code in a module, and I run this module with Python directly, so not in a Notebook context and not in a Bokeh server context.

```python
import hvplot.pandas
from bokeh.sampledata.autompg import autompg

def autompg_plot(x='mpg', y='hp', color='#058805'):
    return autompg.hvplot.scatter(x, y, c=color, padding=0.1)

columns = list(autompg.columns[:-2])
autompg_plot()
import panel as pn
pn.extension()
def fn(a,b): return f'Arguments: {a,b}'
slider = pn.widgets.FloatSlider(value=0.5)

bound_fn = pn.bind(fn, a=slider, b=2)
bound_fn()
pn.Row(slider, bound_fn)
x = pn.widgets.Select(value='mpg', options=columns, name='x')
y = pn.widgets.Select(value='hp', options=columns, name='y')
color = pn.widgets.ColorPicker(name='Color', value='#AA0505')

pn.Row(pn.Column('## MPG Explorer', x, y, color),
       pn.bind(autompg.hvplot.scatter, x, y, c=color))
x = pn.widgets.Select(value='mpg', options=columns, name='x')
y = pn.widgets.Select(value='hp', options=columns, name='y')
color = pn.widgets.ColorPicker(name='Color', value='#AA0505')

@pn.depends(x, y, color)
def plot(xval, yval, colorval):
    return autompg.hvplot.scatter(xval, yval, c=colorval)

pn.Row(
    pn.Column('## MPG Explorer', x, y, color),
    plot
)
color = pn.widgets.ColorPicker(name='Color', value='#4f4fdf')
layout = pn.interact(autompg_plot, x=columns, y=columns, color=color)

pn.Row(pn.Column('## MPG Explorer', layout[0]), layout[1])
import param

class MPGExplorer(param.Parameterized):

    x = param.Selector(objects=columns)
    y = param.Selector(default='hp', objects=columns)
    color = param.Color(default='#0f0f0f')

    @param.depends('x', 'y', 'color') # optional in this case
    def plot(self):
        return autompg_plot(self.x, self.y, self.color)

explorer = MPGExplorer()

pn.Row(explorer.param, explorer.plot)
x = pn.widgets.Select(value='mpg', options=columns, name='x')
y = pn.widgets.Select(value='hp', options=columns, name='y')
color = pn.widgets.ColorPicker(name='Color', value='#880588')

layout = pn.Row(
    pn.Column('## MPG Explorer', x, y, color),
    autompg_plot(x.value, y.value, color.value))

def update(event):
    layout[1].object = autompg_plot(x.value, y.value, color.value)

x.param.watch(update, 'value')
y.param.watch(update, 'value')
color.param.watch(update, 'value')

layout
```

The error I see doesn't happen every time, I have to run the module multiple times to get a chance to see it. Here's the traceback:

```
Traceback (most recent call last):
  File "panel/tests/issue.py", line 31, in <module>
    pn.Row(
  File "/Users/mliquet/work/dev/panel/panel/layout/base.py", line 630, in __init__
    params['objects'] = [panel(pane) for pane in objects]
  File "/Users/mliquet/work/dev/panel/panel/layout/base.py", line 630, in <listcomp>
    params['objects'] = [panel(pane) for pane in objects]
  File "/Users/mliquet/work/dev/panel/panel/pane/base.py", line 84, in panel
    pane = PaneBase.get_pane_type(obj, **kwargs)(obj, **kwargs)
  File "/Users/mliquet/work/dev/panel/panel/param.py", line 790, in __init__
    self._replace_pane()
  File "/Users/mliquet/work/dev/panel/panel/param.py", line 842, in _replace_pane
    new_object = self.eval(self.object)
  File "/Users/mliquet/work/dev/panel/panel/param.py", line 822, in eval
    return function(*args, **kwargs)
  File "/Users/mliquet/work/dev/param/param/parameterized.py", line 407, in _depends
    return func(*args, **kw)
  File "panel/tests/issue.py", line 29, in plot
    return autompg.hvplot.scatter(xval, yval, c=colorval)
  File "/Users/mliquet/miniconda3/envs/panel-dev38/lib/python3.8/site-packages/hvplot/plotting/core.py", line 492, in scatter
    return self(x, y, kind="scatter", **kwds)
  File "/Users/mliquet/miniconda3/envs/panel-dev38/lib/python3.8/site-packages/hvplot/plotting/core.py", line 130, in __call__
    return self._get_converter(x, y, kind, **kwds)(kind, x, y)
  File "/Users/mliquet/miniconda3/envs/panel-dev38/lib/python3.8/site-packages/hvplot/converter.py", line 1228, in __call__
    obj = method(x, y)
  File "/Users/mliquet/miniconda3/envs/panel-dev38/lib/python3.8/site-packages/hvplot/converter.py", line 1641, in scatter
    return self.chart(Scatter, x, y, data)
  File "/Users/mliquet/miniconda3/envs/panel-dev38/lib/python3.8/site-packages/hvplot/converter.py", line 1599, in chart
    return self.single_chart(element, x, y, data)
  File "/Users/mliquet/miniconda3/envs/panel-dev38/lib/python3.8/site-packages/hvplot/converter.py", line 1522, in single_chart
    return (chart.redim(**self._redim)
  File "/Users/mliquet/miniconda3/envs/panel-dev38/lib/python3.8/site-packages/holoviews/core/accessors.py", line 45, in pipelined_call
    result = __call__(*args, **kwargs)
  File "/Users/mliquet/miniconda3/envs/panel-dev38/lib/python3.8/site-packages/holoviews/core/accessors.py", line 571, in __call__
    return self._dispatch_opts( *args, **kwargs)
  File "/Users/mliquet/miniconda3/envs/panel-dev38/lib/python3.8/site-packages/holoviews/core/accessors.py", line 575, in _dispatch_opts
    return self._base_opts(*args, **kwargs)
  File "/Users/mliquet/miniconda3/envs/panel-dev38/lib/python3.8/site-packages/holoviews/core/accessors.py", line 654, in _base_opts
    return self._obj.options(*new_args, **kwargs)
  File "/Users/mliquet/miniconda3/envs/panel-dev38/lib/python3.8/site-packages/holoviews/core/data/__init__.py", line 204, in pipelined_fn
    result = method_fn(*args, **kwargs)
  File "/Users/mliquet/miniconda3/envs/panel-dev38/lib/python3.8/site-packages/holoviews/core/data/__init__.py", line 1212, in options
    return super(Dataset, self).options(*args, **kwargs)
  File "/Users/mliquet/miniconda3/envs/panel-dev38/lib/python3.8/site-packages/holoviews/core/dimension.py", line 1284, in options
    obj = obj.opts._dispatch_opts(expanded, backend=backend, clone=clone)
  File "/Users/mliquet/miniconda3/envs/panel-dev38/lib/python3.8/site-packages/holoviews/core/accessors.py", line 575, in _dispatch_opts
    return self._base_opts(*args, **kwargs)
  File "/Users/mliquet/miniconda3/envs/panel-dev38/lib/python3.8/site-packages/holoviews/core/accessors.py", line 651, in _base_opts
    return opts.apply_groups(self._obj, **dict(kwargs, **new_kwargs))
  File "/Users/mliquet/miniconda3/envs/panel-dev38/lib/python3.8/site-packages/holoviews/util/__init__.py", line 225, in apply_groups
    obj = cls._apply_groups_to_backend(obj, backend_opts, backend, clone)
  File "/Users/mliquet/miniconda3/envs/panel-dev38/lib/python3.8/site-packages/holoviews/util/__init__.py", line 150, in _apply_groups_to_backend
    return StoreOptions.set_options(obj_handle, options, backend=backend)
  File "/Users/mliquet/miniconda3/envs/panel-dev38/lib/python3.8/site-packages/holoviews/core/options.py", line 1870, in set_options
    custom_trees, id_mapping = cls.create_custom_trees(obj, spec, backend=backend)
  File "/Users/mliquet/miniconda3/envs/panel-dev38/lib/python3.8/site-packages/holoviews/core/options.py", line 1656, in create_custom_trees
    offset = cls.id_offset()
  File "/Users/mliquet/miniconda3/envs/panel-dev38/lib/python3.8/site-packages/holoviews/core/options.py", line 1793, in id_offset
    max_id = max(store_ids)+1 if len(store_ids) > 0 else 0
ValueError: max() arg is an empty sequence
```

The error occurs in this classmethod: https://github.com/holoviz/holoviews/blob/e9e97e955e652fa9a6f773f6688f8e3d91685da4/holoviews/core/options.py#L1782-L1794

Now, here's a few very strange things. If I add a `print` (e.g. `print('bob')`) statement **before** `max_id = max(store_ids)+1 if len(store_ids) > 0 else 0`, I no longer manage to trigger the error. I'm not sure if I I just miss it, but it seems to have an effect somehow. That's not very useful anyway, if I replace it by something more useful like `print(store_ids)` I see what being printed isn't consistent, I either get:

```
dict_keys([])
dict_keys([0])
dict_keys([])
dict_keys([0])
dict_keys([2])
dict_keys([3])
dict_keys([8])
dict_keys([8, 9])
dict_keys([8, 20])
dict_keys([8, 20, 21])
dict_keys([8, 20, 44])
dict_keys([8, 20, 44, 45])
```

or

```
dict_keys([])
dict_keys([0])
dict_keys([])
dict_keys([0])
dict_keys([])
dict_keys([0])
dict_keys([2])
dict_keys([2, 3])
dict_keys([2, 8])
dict_keys([2, 8, 9])
dict_keys([2, 8, 20])
dict_keys([2, 8, 20, 21])
```

Removing `print` statements, if I comment `pn.extension()` in the module I no longer manage to trigger to error and I consistently get the following, that is different from the two output I got above:

```
dict_keys([])
dict_keys([0])
dict_keys([])
dict_keys([0])
dict_keys([2])
dict_keys([2, 3])
dict_keys([2, 8])
dict_keys([2, 8, 9])
dict_keys([8, 20])
dict_keys([8, 20, 21])
dict_keys([8, 20, 44])
dict_keys([8, 20, 44, 45])
```

@Hoxbro could you try to reproduce that please? (I'm using this to run it multiple times `for a in {1..10}; do python issue.py; done`)

**Comment by Hoxbro** [comment]
I think this is the same as https://github.com/holoviz/holoviews/issues/5430

**Comment by maximlt** [comment]
Thanks, interesting to see another issue with the same symptoms.

You suggestion seems to work on my use case. But well, I feel it's hiding a more profound problem, isn't it?
