### ISSUE TITLE
Docs: Install instructions for holoviews don't work correctly with new libmamba solver

### ISSUE THREAD

**Issue by sandhujasmine** [holoviz/holoviews#5547]
#### ALL software version info
[Documentation on installation](https://github.com/holoviz/holoviews#installation).  This looks like an issue with the libmamba solver so should also be asked about / logged in `conda`. But using `conda install -c pyviz holoviews` is sufficient and works consistently; however, `conda install -c holoviews bokeh` does not.

#### Description of expected behavior and the observed behavior

It seems `conda install -c pyviz holoviews` installs the correct bokeh dependency. I don't know why we need to install `bokeh` separately; although I would expect `conda install -c pyviz holoviews bokeh` and `conda install -c pyviz holoviews` to install the same set of packages. I'll also raise this issue in the conda channel. I think this is related to the libmamba solver. If I use the classic solver, I get the correct version of bokeh (2.4.3). But I couldn't fully test since `python -c 'import holoview'` raised a linkage issue when using the classic solver - haven't dug into that yet.

```
% conda create -n hv_test -c pyviz holoviews bokeh
conda list -n hv_test 'bokeh|holoviews|panel'
# packages in environment at /Users/jasmine/miniconda3/envs/hv_test:
#
# Name                    Version                   Build  Channel
bokeh                     3.0.2           py310hca03da5_0    defaults
holoviews                 1.14.9                     py_0    pyviz
panel                     0.10.3                     py_0    pyviz
```

Compare this to only installing the holoviews package with the libmamba solver which installs correct bokeh version:

```
% conda create -n only_hv -c pyviz holoviews
% conda list -n only_hv 'bokeh|holoviews|panel'
# packages in environment at /Users/jasmine/miniconda3/envs/only_hv:
#
# Name                    Version                   Build  Channel
bokeh                     2.4.3           py310hca03da5_0    defaults
holoviews                 1.15.2                     py_0    pyviz
panel                     0.14.1                     py_0    pyviz
```

#### Complete, minimal, self-contained example code that reproduces the issue

```

# this breaks when using the libmamba solver since that installs latest bokeh dependency
conda create -n hv -c pyviz holoviews bokeh

# this works with the libmamba solver since it installs bokeh version 2.4.3
conda create -n hv -c pyviz holoviews

```

#### Stack traceback and/or browser JavaScript console output

```
% conda create -n hv -c pyviz holoviews
% conda activate hv
% python -c 'import holoviews'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/jasmine/miniconda3/envs/hv_test/lib/python3.10/site-packages/holoviews/__init__.py", line 12, in <module>
    from .annotators import annotate                         # noqa (API import)
  File "/Users/jasmine/miniconda3/envs/hv_test/lib/python3.10/site-packages/holoviews/annotators.py", line 10, in <module>
    from panel.pane import PaneBase
  File "/Users/jasmine/miniconda3/envs/hv_test/lib/python3.10/site-packages/panel/__init__.py", line 3, in <module>
    from . import layout # noqa
  File "/Users/jasmine/miniconda3/envs/hv_test/lib/python3.10/site-packages/panel/layout/__init__.py", line 1, in <module>
    from .accordion import Accordion # noqa
  File "/Users/jasmine/miniconda3/envs/hv_test/lib/python3.10/site-packages/panel/layout/accordion.py", line 5, in <module>
    from .base import NamedListPanel
  File "/Users/jasmine/miniconda3/envs/hv_test/lib/python3.10/site-packages/panel/layout/base.py", line 13, in <module>
    from ..io.model import hold
  File "/Users/jasmine/miniconda3/envs/hv_test/lib/python3.10/site-packages/panel/io/__init__.py", line 8, in <module>
    from ..config import config
  File "/Users/jasmine/miniconda3/envs/hv_test/lib/python3.10/site-packages/panel/config.py", line 20, in <module>
    from .io.notebook import load_notebook
  File "/Users/jasmine/miniconda3/envs/hv_test/lib/python3.10/site-packages/panel/io/notebook.py", line 40, in <module>
    from .embed import embed_state
  File "/Users/jasmine/miniconda3/envs/hv_test/lib/python3.10/site-packages/panel/io/embed.py", line 20, in <module>
    from .model import add_to_doc, diff
  File "/Users/jasmine/miniconda3/envs/hv_test/lib/python3.10/site-packages/panel/io/model.py", line 11, in <module>
    from bokeh.models import Box, ColumnDataSource, Model
ImportError: cannot import name 'Box' from 'bokeh.models' (/Users/jasmine/miniconda3/envs/hv_test/lib/python3.10/site-packages/bokeh/models/__init__.py)
```

**Comment by sandhujasmine** [comment]
In the holoviews [`setup.py`](https://github.com/holoviz/holoviews/blob/master/setup.py#L80-L83) bokeh is a recommended extra and it's version is not upper bound.

However, [`panel`](https://github.com/holoviz/holoviews/blob/master/setup.py#L13-L21) is a required dependency. And the stack above is raised by the panel library. Panel itself has bounds on `bokeh` version likely because of the above error - looking at [panel's `setup.py`](https://github.com/holoviz/panel/blob/master/setup.py#L105-L116).

**Comment by sandhujasmine** [comment]
Quoting @jbednar from slack. 

"Ok, I think this explains the difference. HoloViz tools are not compatible with Bokeh 3.0, and won't be for some time. My guess is that if bokeh is specified on the command line, and panel is not, libmamba prefers the latest version of both holoviews and bokeh, and the only way to achieve that is by selecting an ancient version of Panel that did not pin to bokeh < 3. Thus the solve is technically correct and not a bug; the bug is with the ecosystem, because there are packages that fail to declare that they are incompatible with Bokeh < 3 (all available versions of Panel and HoloViews and hvPlot)."

Thanks Jim for solving the mystery for me. A simple fix on our end is to remove bokeh from the install instructions and let `panel` install it as a dependency.
