### ISSUE TITLE
Dask DataFrame + Lasso select linked brushing not working

### ISSUE THREAD

**Issue by mmorys** [holoviz/holoviews#5567]
IMPORTANT: I have narrowed down the problem to the following line of code. Assignment like this is not supported by Dask. I will submit an accompanying pull request with a proposed fix.
https://github.com/holoviz/holoviews/blob/f7017e3012ef60d7368676d1c87efe8194d03a1e/holoviews/element/selection.py#L120 

#### ALL software version info
python=3.10.8
bokeh=2.4.3
dask=2022.12.0
datashader=0.14.3
holoviews=1.15.3
numpy=1.23.5
pandas=1.5.2
panel=0.14.1
spatialpandas=0.4.5

#### Description of expected behavior and the observed behavior
Attempting to lasso-select points that are backed by a Dask DataFrame results in an error. Box select works fine, but lasso select does not. This issue exists for both datashaded and non-datshaded plots. Same result using spatialpandas and shapely.

#### Complete, minimal, self-contained example code that reproduces the issue

```python
import dask.dataframe as dd
import holoviews as hv
import panel as pn
from holoviews.operation.datashader import datashade
from numpy.random import randn


hv.extension("bokeh")

df = dd.from_dict({"x": randn(1000), "y": randn(1000)}, npartitions=2)

link = hv.link_selections.instance()

non_datashaded_plot = link(hv.Points(df))
datashaded_plot = link(datashade(hv.Points(df)))
pn.Column(non_datashaded_plot + datashaded_plot).show()

# Error will occur when you try to lasso-select data in either plot
```

#### Stack traceback and/or browser JavaScript console output
```shell
WARNING:param.dynamic_operation: Callable raised "CallbackError('linked_selection aborted because it could not display selection for all elements: only integer scalar arrays can be converted to a scalar index.')".
Invoked as dynamic_operation(cmap=None, exprs=[True, dim('x', spatial_select, dim('y'), geometry=array([[ 1.81901611,  0.02067943],
       [ 1.9212558 ,  0.3637043 ],
       [ 1.853096  ,  0.70672917],
       [ 1.27373776,  0.73791325],
       [-0.70289623,  0.64436101],
       [-2.23649157,  0.33252022],
       [-2.88400961, -0.04168873],
       [-3.25888847, -0.66537031],
       [-3.49744774, -1.66326085],
       [-3.39520805, -2.50523099],
       [-2.9862493 , -3.12891257],
       [-2.54321064, -3.5343056 ],
       [-1.92977251, -3.690226  ],
       [-1.45265396, -3.72141008],
       [-1.14593489, -3.72141008],
       [-1.0096153 , -3.690226  ],
       [-0.80513592, -3.65904192],
       [-0.77105603, -3.62785784],
       [-0.77105603, -3.62785784]]))])
WARNING:param.dynamic_operation: Callable raised "CallbackError('linked_selection aborted because it could not display selection for all elements: only integer scalar arrays can be converted to a scalar index.')".
Invoked as dynamic_operation(alpha=0.1, colors=[None, None], cmap=None)
WARNING:param.dynamic_operation: Callable raised "CallbackError('linked_selection aborted because it could not display selection for all elements: only integer scalar arrays can be converted to a scalar index.')".
Invoked as dynamic_operation(cmap=None, exprs=[True, dim('x', spatial_select, dim('y'), geometry=array([[ 1.81901611,  0.02067943],
       [ 1.9212558 ,  0.3637043 ],
       [ 1.853096  ,  0.70672917],
       [ 1.27373776,  0.73791325],
       [-0.70289623,  0.64436101],
       [-2.23649157,  0.33252022],
       [-2.88400961, -0.04168873],
       [-3.25888847, -0.66537031],
       [-3.49744774, -1.66326085],
       [-3.39520805, -2.50523099],
       [-2.9862493 , -3.12891257],
       [-2.54321064, -3.5343056 ],
       [-1.92977251, -3.690226  ],
       [-1.45265396, -3.72141008],
       [-1.14593489, -3.72141008],
       [-1.0096153 , -3.690226  ],
       [-0.80513592, -3.65904192],
       [-0.77105603, -3.62785784],
       [-0.77105603, -3.62785784]]))])
WARNING:param.dynamic_operation: Callable raised "CallbackError('linked_selection aborted because it could not display selection for all elements: only integer scalar arrays can be converted to a scalar index.')".
Invoked as dynamic_operation(alpha=0.1, colors=[None, None], cmap=None)
WARNING:param.dynamic_operation: Callable raised "CallbackError('linked_selection aborted because it could not display selection for all elements: only integer scalar arrays can be converted to a scalar index.')".
Invoked as dynamic_operation(cmap=None, exprs=[True, dim('x', spatial_select, dim('y'), geometry=array([[ 1.81901611,  0.02067943],
       [ 1.9212558 ,  0.3637043 ],
       [ 1.853096  ,  0.70672917],
       [ 1.27373776,  0.73791325],
       [-0.70289623,  0.64436101],
       [-2.23649157,  0.33252022],
       [-2.88400961, -0.04168873],
       [-3.25888847, -0.66537031],
       [-3.49744774, -1.66326085],
       [-3.39520805, -2.50523099],
       [-2.9862493 , -3.12891257],
       [-2.54321064, -3.5343056 ],
       [-1.92977251, -3.690226  ],
       [-1.45265396, -3.72141008],
       [-1.14593489, -3.72141008],
       [-1.0096153 , -3.690226  ],
       [-0.80513592, -3.65904192],
       [-0.77105603, -3.62785784],
       [-0.77105603, -3.62785784]]))])
WARNING:param.dynamic_operation: Callable raised "CallbackError('linked_selection aborted because it could not display selection for all elements: only integer scalar arrays can be converted to a scalar index.')".
Invoked as dynamic_operation(alpha=0.1, colors=[None, None], cmap=None)
Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOMainLoop object at 0x7fb2d03e7610>>, <Task finished name='Task-1101' coro=<ServerSession.with_document_locked() done, defined at /user_environment/lib/python3.10/site-packages/bokeh/server/session.py:78> exception=CallbackError('linked_selection aborted because it could not display selection for all elements: only integer scalar arrays can be converted to a scalar index.')>)
Traceback (most recent call last):
  File "/user_environment/lib/python3.10/site-packages/holoviews/selection.py", line 511, in _select
    mask = selection_expr.apply(dataset, compute=False, keep_index=True, strict=False)
  File "/user_environment/lib/python3.10/site-packages/holoviews/util/transform.py", line 773, in apply
    data = self._apply_fn(dataset, data, fn, fn_name, args,
  File "/user_environment/lib/python3.10/site-packages/holoviews/util/transform.py", line 673, in _apply_fn
    data = fn(*args, **kwargs)
  File "/user_environment/lib/python3.10/site-packages/holoviews/element/selection.py", line 128, in spatial_select
    return spatial_select_columnar(xvals, yvals, geometry)
  File "/user_environment/lib/python3.10/site-packages/holoviews/element/selection.py", line 120, in spatial_select_columnar
    mask[np.where(mask)[0]] = geom_mask
TypeError: only integer scalar arrays can be converted to a scalar index

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/user_environment/lib/python3.10/site-packages/tornado/ioloop.py", line 740, in _run_callback
    ret = callback()
  File "/user_environment/lib/python3.10/site-packages/tornado/ioloop.py", line 764, in _discard_future_result
    future.result()
  File "/user_environment/lib/python3.10/site-packages/bokeh/server/session.py", line 95, in _needs_document_lock_wrapper
    result = func(self, *args, **kwargs)
  File "/user_environment/lib/python3.10/site-packages/bokeh/server/session.py", line 229, in with_document_locked
    return func(*args, **kwargs)
  File "/user_environment/lib/python3.10/site-packages/bokeh/document/callbacks.py", line 450, in wrapper
    return invoke_with_curdoc(doc, invoke)
  File "/user_environment/lib/python3.10/site-packages/bokeh/document/callbacks.py", line 408, in invoke_with_curdoc
    return f()
  File "/user_environment/lib/python3.10/site-packages/bokeh/document/callbacks.py", line 449, in invoke
    return f(*args, **kwargs)
  File "/user_environment/lib/python3.10/site-packages/bokeh/document/callbacks.py", line 179, in remove_then_invoke
    return callback()
  File "/user_environment/lib/python3.10/site-packages/holoviews/plotting/plot.py", line 243, in refresh
    raise e
  File "/user_environment/lib/python3.10/site-packages/holoviews/plotting/plot.py", line 239, in refresh
    self._trigger_refresh(stream_key)
  File "/user_environment/lib/python3.10/site-packages/holoviews/plotting/plot.py", line 256, in _trigger_refresh
    self.update(key)
  File "/user_environment/lib/python3.10/site-packages/holoviews/plotting/plot.py", line 949, in update
    item = self.__getitem__(key)
  File "/user_environment/lib/python3.10/site-packages/holoviews/plotting/plot.py", line 435, in __getitem__
    self.update_frame(frame)
  File "/user_environment/lib/python3.10/site-packages/holoviews/plotting/bokeh/element.py", line 2410, in update_frame
    element = self._get_frame(key)
  File "/user_environment/lib/python3.10/site-packages/holoviews/plotting/plot.py", line 1259, in _get_frame
    frame = get_plot_frame(self.hmap, key_map, cached)
  File "/user_environment/lib/python3.10/site-packages/holoviews/plotting/util.py", line 284, in get_plot_frame
    raise e
  File "/user_environment/lib/python3.10/site-packages/holoviews/plotting/util.py", line 280, in get_plot_frame
    return map_obj[key]
  File "/user_environment/lib/python3.10/site-packages/holoviews/core/spaces.py", line 1216, in __getitem__
    val = self._execute_callback(*tuple_key)
  File "/user_environment/lib/python3.10/site-packages/holoviews/core/spaces.py", line 983, in _execute_callback
    retval = self.callback(*args, **kwargs)
  File "/user_environment/lib/python3.10/site-packages/holoviews/core/spaces.py", line 550, in __call__
    if not args and not kwargs and not any(kwarg_hash): return self.callable()
  File "/user_environment/lib/python3.10/site-packages/holoviews/core/spaces.py", line 199, in dynamic_mul
    self_el = self.select(HoloMap, **key_map) if self.kdims else self[()]
  File "/user_environment/lib/python3.10/site-packages/holoviews/core/spaces.py", line 1216, in __getitem__
    val = self._execute_callback(*tuple_key)
  File "/user_environment/lib/python3.10/site-packages/holoviews/core/spaces.py", line 983, in _execute_callback
    retval = self.callback(*args, **kwargs)
  File "/user_environment/lib/python3.10/site-packages/holoviews/core/spaces.py", line 550, in __call__
    if not args and not kwargs and not any(kwarg_hash): return self.callable()
  File "/user_environment/lib/python3.10/site-packages/holoviews/core/spaces.py", line 204, in dynamic_mul
    other_el = other.select(HoloMap, **key_map) if other.kdims else other[()]
  File "/user_environment/lib/python3.10/site-packages/holoviews/core/spaces.py", line 1216, in __getitem__
    val = self._execute_callback(*tuple_key)
  File "/user_environment/lib/python3.10/site-packages/holoviews/core/spaces.py", line 983, in _execute_callback
    retval = self.callback(*args, **kwargs)
  File "/user_environment/lib/python3.10/site-packages/holoviews/core/spaces.py", line 581, in __call__
    ret = self.callable(*args, **kwargs)
  File "/user_environment/lib/python3.10/site-packages/holoviews/util/__init__.py", line 1012, in dynamic_operation
    key, obj = resolve(key, kwargs)
  File "/user_environment/lib/python3.10/site-packages/holoviews/util/__init__.py", line 1001, in resolve
    return key, map_obj[key]
  File "/user_environment/lib/python3.10/site-packages/holoviews/core/spaces.py", line 1216, in __getitem__
    val = self._execute_callback(*tuple_key)
  File "/user_environment/lib/python3.10/site-packages/holoviews/core/spaces.py", line 983, in _execute_callback
    retval = self.callback(*args, **kwargs)
  File "/user_environment/lib/python3.10/site-packages/holoviews/core/spaces.py", line 581, in __call__
    ret = self.callable(*args, **kwargs)
  File "/user_environment/lib/python3.10/site-packages/holoviews/util/__init__.py", line 1013, in dynamic_operation
    return apply(obj, *key, **kwargs)
  File "/user_environment/lib/python3.10/site-packages/holoviews/util/__init__.py", line 1005, in apply
    processed = self._process(element, key, kwargs)
  File "/user_environment/lib/python3.10/site-packages/holoviews/util/__init__.py", line 989, in _process
    return self.p.operation(element, **kwargs)
  File "/user_environment/lib/python3.10/site-packages/holoviews/selection.py", line 612, in _build_layer_callback
    selection = self._select(element, exprs[layer_number], cache)
  File "/user_environment/lib/python3.10/site-packages/holoviews/selection.py", line 519, in _select
    raise CallbackError("linked_selection aborted because it could not "
holoviews.core.options.CallbackError: linked_selection aborted because it could not display selection for all elements: only integer scalar arrays can be converted to a scalar index.
Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOMainLoop object at 0x7fb2d03e7610>>, <Task finished name='Task-1102' coro=<ServerSession.with_document_locked() done, defined at /user_environment/lib/python3.10/site-packages/bokeh/server/session.py:78> exception=CallbackError('linked_selection aborted because it could not display selection for all elements: only integer scalar arrays can be converted to a scalar index.')>)
Traceback (most recent call last):
  File "/user_environment/lib/python3.10/site-packages/holoviews/selection.py", line 511, in _select
    mask = selection_expr.apply(dataset, compute=False, keep_index=True, strict=False)
  File "/user_environment/lib/python3.10/site-packages/holoviews/util/transform.py", line 773, in apply
    data = self._apply_fn(dataset, data, fn, fn_name, args,
  File "/user_environment/lib/python3.10/site-packages/holoviews/util/transform.py", line 673, in _apply_fn
    data = fn(*args, **kwargs)
  File "/user_environment/lib/python3.10/site-packages/holoviews/element/selection.py", line 128, in spatial_select
    return spatial_select_columnar(xvals, yvals, geometry)
  File "/user_environment/lib/python3.10/site-packages/holoviews/element/selection.py", line 120, in spatial_select_columnar
    mask[np.where(mask)[0]] = geom_mask
TypeError: only integer scalar arrays can be converted to a scalar index

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/user_environment/lib/python3.10/site-packages/tornado/ioloop.py", line 740, in _run_callback
    ret = callback()
  File "/user_environment/lib/python3.10/site-packages/tornado/ioloop.py", line 764, in _discard_future_result
    future.result()
  File "/user_environment/lib/python3.10/site-packages/bokeh/server/session.py", line 95, in _needs_document_lock_wrapper
    result = func(self, *args, **kwargs)
  File "/user_environment/lib/python3.10/site-packages/bokeh/server/session.py", line 229, in with_document_locked
    return func(*args, **kwargs)
  File "/user_environment/lib/python3.10/site-packages/bokeh/document/callbacks.py", line 450, in wrapper
    return invoke_with_curdoc(doc, invoke)
  File "/user_environment/lib/python3.10/site-packages/bokeh/document/callbacks.py", line 408, in invoke_with_curdoc
    return f()
  File "/user_environment/lib/python3.10/site-packages/bokeh/document/callbacks.py", line 449, in invoke
    return f(*args, **kwargs)
  File "/user_environment/lib/python3.10/site-packages/bokeh/document/callbacks.py", line 179, in remove_then_invoke
    return callback()
  File "/user_environment/lib/python3.10/site-packages/holoviews/plotting/plot.py", line 243, in refresh
    raise e
  File "/user_environment/lib/python3.10/site-packages/holoviews/plotting/plot.py", line 239, in refresh
    self._trigger_refresh(stream_key)
  File "/user_environment/lib/python3.10/site-packages/holoviews/plotting/plot.py", line 256, in _trigger_refresh
    self.update(key)
  File "/user_environment/lib/python3.10/site-packages/holoviews/plotting/plot.py", line 949, in update
    item = self.__getitem__(key)
  File "/user_environment/lib/python3.10/site-packages/holoviews/plotting/plot.py", line 435, in __getitem__
    self.update_frame(frame)
  File "/user_environment/lib/python3.10/site-packages/holoviews/plotting/bokeh/element.py", line 2410, in update_frame
    element = self._get_frame(key)
  File "/user_environment/lib/python3.10/site-packages/holoviews/plotting/plot.py", line 1259, in _get_frame
    frame = get_plot_frame(self.hmap, key_map, cached)
  File "/user_environment/lib/python3.10/site-packages/holoviews/plotting/util.py", line 284, in get_plot_frame
    raise e
  File "/user_environment/lib/python3.10/site-packages/holoviews/plotting/util.py", line 280, in get_plot_frame
    return map_obj[key]
  File "/user_environment/lib/python3.10/site-packages/holoviews/core/spaces.py", line 1216, in __getitem__
    val = self._execute_callback(*tuple_key)
  File "/user_environment/lib/python3.10/site-packages/holoviews/core/spaces.py", line 983, in _execute_callback
    retval = self.callback(*args, **kwargs)
  File "/user_environment/lib/python3.10/site-packages/holoviews/core/spaces.py", line 550, in __call__
    if not args and not kwargs and not any(kwarg_hash): return self.callable()
  File "/user_environment/lib/python3.10/site-packages/holoviews/core/spaces.py", line 199, in dynamic_mul
    self_el = self.select(HoloMap, **key_map) if self.kdims else self[()]
  File "/user_environment/lib/python3.10/site-packages/holoviews/core/spaces.py", line 1216, in __getitem__
    val = self._execute_callback(*tuple_key)
  File "/user_environment/lib/python3.10/site-packages/holoviews/core/spaces.py", line 983, in _execute_callback
    retval = self.callback(*args, **kwargs)
  File "/user_environment/lib/python3.10/site-packages/holoviews/core/spaces.py", line 550, in __call__
    if not args and not kwargs and not any(kwarg_hash): return self.callable()
  File "/user_environment/lib/python3.10/site-packages/holoviews/core/spaces.py", line 204, in dynamic_mul
    other_el = other.select(HoloMap, **key_map) if other.kdims else other[()]
  File "/user_environment/lib/python3.10/site-packages/holoviews/core/spaces.py", line 1216, in __getitem__
    val = self._execute_callback(*tuple_key)
  File "/user_environment/lib/python3.10/site-packages/holoviews/core/spaces.py", line 983, in _execute_callback
    retval = self.callback(*args, **kwargs)
  File "/user_environment/lib/python3.10/site-packages/holoviews/core/spaces.py", line 581, in __call__
    ret = self.callable(*args, **kwargs)
  File "/user_environment/lib/python3.10/site-packages/holoviews/util/__init__.py", line 1012, in dynamic_operation
    key, obj = resolve(key, kwargs)
  File "/user_environment/lib/python3.10/site-packages/holoviews/util/__init__.py", line 1001, in resolve
    return key, map_obj[key]
  File "/user_environment/lib/python3.10/site-packages/holoviews/core/spaces.py", line 1216, in __getitem__
    val = self._execute_callback(*tuple_key)
  File "/user_environment/lib/python3.10/site-packages/holoviews/core/spaces.py", line 983, in _execute_callback
    retval = self.callback(*args, **kwargs)
  File "/user_environment/lib/python3.10/site-packages/holoviews/core/spaces.py", line 581, in __call__
    ret = self.callable(*args, **kwargs)
  File "/user_environment/lib/python3.10/site-packages/holoviews/util/__init__.py", line 1013, in dynamic_operation
    return apply(obj, *key, **kwargs)
  File "/user_environment/lib/python3.10/site-packages/holoviews/util/__init__.py", line 1005, in apply
    processed = self._process(element, key, kwargs)
  File "/user_environment/lib/python3.10/site-packages/holoviews/util/__init__.py", line 989, in _process
    return self.p.operation(element, **kwargs)
  File "/user_environment/lib/python3.10/site-packages/holoviews/selection.py", line 612, in _build_layer_callback
    selection = self._select(element, exprs[layer_number], cache)
  File "/user_environment/lib/python3.10/site-packages/holoviews/selection.py", line 519, in _select
    raise CallbackError("linked_selection aborted because it could not "
holoviews.core.options.CallbackError: linked_selection aborted because it could not display selection for all elements: only integer scalar arrays can be converted to a scalar index.
Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOMainLoop object at 0x7fb2d03e7610>>, <Task finished name='Task-1104' coro=<ServerSession.with_document_locked() done, defined at /user_environment/lib/python3.10/site-packages/bokeh/server/session.py:78> exception=CallbackError('linked_selection aborted because it could not display selection for all elements: only integer scalar arrays can be converted to a scalar index.')>)
Traceback (most recent call last):
  File "/user_environment/lib/python3.10/site-packages/holoviews/selection.py", line 511, in _select
    mask = selection_expr.apply(dataset, compute=False, keep_index=True, strict=False)
  File "/user_environment/lib/python3.10/site-packages/holoviews/util/transform.py", line 773, in apply
    data = self._apply_fn(dataset, data, fn, fn_name, args,
  File "/user_environment/lib/python3.10/site-packages/holoviews/util/transform.py", line 673, in _apply_fn
    data = fn(*args, **kwargs)
  File "/user_environment/lib/python3.10/site-packages/holoviews/element/selection.py", line 128, in spatial_select
    return spatial_select_columnar(xvals, yvals, geometry)
  File "/user_environment/lib/python3.10/site-packages/holoviews/element/selection.py", line 120, in spatial_select_columnar
    mask[np.where(mask)[0]] = geom_mask
TypeError: only integer scalar arrays can be converted to a scalar index

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/user_environment/lib/python3.10/site-packages/tornado/ioloop.py", line 740, in _run_callback
    ret = callback()
  File "/user_environment/lib/python3.10/site-packages/tornado/ioloop.py", line 764, in _discard_future_result
    future.result()
  File "/user_environment/lib/python3.10/site-packages/bokeh/server/session.py", line 95, in _needs_document_lock_wrapper
    result = func(self, *args, **kwargs)
  File "/user_environment/lib/python3.10/site-packages/bokeh/server/session.py", line 229, in with_document_locked
    return func(*args, **kwargs)
  File "/user_environment/lib/python3.10/site-packages/bokeh/document/callbacks.py", line 450, in wrapper
    return invoke_with_curdoc(doc, invoke)
  File "/user_environment/lib/python3.10/site-packages/bokeh/document/callbacks.py", line 408, in invoke_with_curdoc
    return f()
  File "/user_environment/lib/python3.10/site-packages/bokeh/document/callbacks.py", line 449, in invoke
    return f(*args, **kwargs)
  File "/user_environment/lib/python3.10/site-packages/bokeh/document/callbacks.py", line 179, in remove_then_invoke
    return callback()
  File "/user_environment/lib/python3.10/site-packages/holoviews/plotting/plot.py", line 243, in refresh
    raise e
  File "/user_environment/lib/python3.10/site-packages/holoviews/plotting/plot.py", line 239, in refresh
    self._trigger_refresh(stream_key)
  File "/user_environment/lib/python3.10/site-packages/holoviews/plotting/plot.py", line 256, in _trigger_refresh
    self.update(key)
  File "/user_environment/lib/python3.10/site-packages/holoviews/plotting/plot.py", line 949, in update
    item = self.__getitem__(key)
  File "/user_environment/lib/python3.10/site-packages/holoviews/plotting/plot.py", line 435, in __getitem__
    self.update_frame(frame)
  File "/user_environment/lib/python3.10/site-packages/holoviews/plotting/bokeh/element.py", line 2410, in update_frame
    element = self._get_frame(key)
  File "/user_environment/lib/python3.10/site-packages/holoviews/plotting/plot.py", line 1259, in _get_frame
    frame = get_plot_frame(self.hmap, key_map, cached)
  File "/user_environment/lib/python3.10/site-packages/holoviews/plotting/util.py", line 284, in get_plot_frame
    raise e
  File "/user_environment/lib/python3.10/site-packages/holoviews/plotting/util.py", line 280, in get_plot_frame
    return map_obj[key]
  File "/user_environment/lib/python3.10/site-packages/holoviews/core/spaces.py", line 1216, in __getitem__
    val = self._execute_callback(*tuple_key)
  File "/user_environment/lib/python3.10/site-packages/holoviews/core/spaces.py", line 983, in _execute_callback
    retval = self.callback(*args, **kwargs)
  File "/user_environment/lib/python3.10/site-packages/holoviews/core/spaces.py", line 550, in __call__
    if not args and not kwargs and not any(kwarg_hash): return self.callable()
  File "/user_environment/lib/python3.10/site-packages/holoviews/core/spaces.py", line 199, in dynamic_mul
    self_el = self.select(HoloMap, **key_map) if self.kdims else self[()]
  File "/user_environment/lib/python3.10/site-packages/holoviews/core/spaces.py", line 1216, in __getitem__
    val = self._execute_callback(*tuple_key)
  File "/user_environment/lib/python3.10/site-packages/holoviews/core/spaces.py", line 983, in _execute_callback
    retval = self.callback(*args, **kwargs)
  File "/user_environment/lib/python3.10/site-packages/holoviews/core/spaces.py", line 550, in __call__
    if not args and not kwargs and not any(kwarg_hash): return self.callable()
  File "/user_environment/lib/python3.10/site-packages/holoviews/core/spaces.py", line 204, in dynamic_mul
    other_el = other.select(HoloMap, **key_map) if other.kdims else other[()]
  File "/user_environment/lib/python3.10/site-packages/holoviews/core/spaces.py", line 1216, in __getitem__
    val = self._execute_callback(*tuple_key)
  File "/user_environment/lib/python3.10/site-packages/holoviews/core/spaces.py", line 983, in _execute_callback
    retval = self.callback(*args, **kwargs)
  File "/user_environment/lib/python3.10/site-packages/holoviews/core/spaces.py", line 581, in __call__
    ret = self.callable(*args, **kwargs)
  File "/user_environment/lib/python3.10/site-packages/holoviews/util/__init__.py", line 1012, in dynamic_operation
    key, obj = resolve(key, kwargs)
  File "/user_environment/lib/python3.10/site-packages/holoviews/util/__init__.py", line 1001, in resolve
    return key, map_obj[key]
  File "/user_environment/lib/python3.10/site-packages/holoviews/core/spaces.py", line 1216, in __getitem__
    val = self._execute_callback(*tuple_key)
  File "/user_environment/lib/python3.10/site-packages/holoviews/core/spaces.py", line 983, in _execute_callback
    retval = self.callback(*args, **kwargs)
  File "/user_environment/lib/python3.10/site-packages/holoviews/core/spaces.py", line 581, in __call__
    ret = self.callable(*args, **kwargs)
  File "/user_environment/lib/python3.10/site-packages/holoviews/util/__init__.py", line 1013, in dynamic_operation
    return apply(obj, *key, **kwargs)
  File "/user_environment/lib/python3.10/site-packages/holoviews/util/__init__.py", line 1005, in apply
    processed = self._process(element, key, kwargs)
  File "/user_environment/lib/python3.10/site-packages/holoviews/util/__init__.py", line 989, in _process
    return self.p.operation(element, **kwargs)
  File "/user_environment/lib/python3.10/site-packages/holoviews/selection.py", line 612, in _build_layer_callback
    selection = self._select(element, exprs[layer_number], cache)
  File "/user_environment/lib/python3.10/site-packages/holoviews/selection.py", line 519, in _select
    raise CallbackError("linked_selection aborted because it could not "
holoviews.core.options.CallbackError: linked_selection aborted because it could not display selection for all elements: only integer scalar arrays can be converted to a scalar index.
```

**Comment by jbednar** [comment]
Thanks so much!
