### ISSUE TITLE
Import of holoviews.plotting.bokeh fails with nightly/dev numpy

### ISSUE THREAD

**Issue by djhoese** [holoviz/holoviews#5635]
#### ALL software version info
Holoviews installed from conda-forge in Python 3.9 environment (not just 3.9) with numpy installed from the nightly builds.

#### Description of expected behavior and the observed behavior

Import fails due to an incompatibility with changes in numpy. Numpy `np.size` is no longer a function, but is rather a callable. This means that we fail when this ClassSelector is created:

https://github.com/holoviz/holoviews/blob/4e83af3e6af0e19fa6c7e226791011372916fc70/holoviews/plotting/bokeh/hex_tiles.py#L26-L30

As `param` will then run:

https://github.com/holoviz/param/blob/cd1b4ae50c01c14c0eb22721e41a9c8fb1e8f738/param/__init__.py#L1381-L1385

```python
        if is_instance:
            if not (isinstance(val, class_)):
                raise ValueError(
                    "%s parameter %r value must be an instance of %s, not %r." %
                    (param_cls, self.name, class_name, val))
```

which fails because `isinstance(np.size, types.FunctionType)` is `False`. See this numpy issue for further discussion:

https://github.com/numpy/numpy/issues/23307

#### Complete, minimal, self-contained example code that reproduces the issue

```
conda create -c conda-forge -n numpy_dev_py311 python=3.11 numpy
conda activate numpy_dev_py311
conda uninstall -y --force numpy
python -m pip install --index-url https://pypi.anaconda.org/scipy-wheels-nightly/simple/ --trusted-host pypi.anaconda.org --no-deps --pre --upgrade numpy
conda install -c conda-forge -y holoviews
python -c "import holoviews.plotting.bokeh"
```

This issue is also seen when importing geoviews based on what it imports by default, but holoviews by itself doesn't fail. Basically it is just this one particular `ClassSelector` from what I can tell.

#### Stack traceback and/or browser JavaScript console output

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/davidh/miniconda3/envs/numpy_dev_py311/lib/python3.11/site-packages/holoviews/plotting/bokeh/__init__.py", line 34, in <module>
    from .hex_tiles import HexTilesPlot
  File "/home/davidh/miniconda3/envs/numpy_dev_py311/lib/python3.11/site-packages/holoviews/plotting/bokeh/hex_tiles.py", line 18, in <module>
    class hex_binning(Operation):
  File "/home/davidh/miniconda3/envs/numpy_dev_py311/lib/python3.11/site-packages/holoviews/plotting/bokeh/hex_tiles.py", line 26, in hex_binning
    aggregator = param.ClassSelector(
                 ^^^^^^^^^^^^^^^^^^^^
  File "/home/davidh/miniconda3/envs/numpy_dev_py311/lib/python3.11/site-packages/param/__init__.py", line 1331, in __init__
    self._validate(default)
  File "/home/davidh/miniconda3/envs/numpy_dev_py311/lib/python3.11/site-packages/param/__init__.py", line 1335, in _validate
    self._validate_class_(val, self.class_, self.is_instance)
  File "/home/davidh/miniconda3/envs/numpy_dev_py311/lib/python3.11/site-packages/param/__init__.py", line 1347, in _validate_class_
    raise ValueError(
ValueError: ClassSelector parameter None value must be an instance of (function, tuple), not <function size at 0x7fa87694be40>.

```

**Comment by shambakey1** [comment]
Hi
I'm trying hvplot 0.9.2, and I'm having the same error every time I try to import it. I wonder if it was solved.

Regards

**Comment by Hoxbro** [comment]
It was, please update to the latest holoviews 1.18.3
