### ISSUE TITLE
hv.Polygons does not work with numpy.datetime64 axis

### ISSUE THREAD

**Issue by wx4stg** [holoviz/holoviews#6068]
bokeh 3.2.2
holoviews 1.18.0
python 3.11.6

Using a points object with a datetime64 kdim as a base, it is impossible to overlay polygons on the same axis. Using datetime64 causes a `TypeError: float() argument must be a string or a real number, not 'datetime.datetime'`

```python3
import holoviews as hv
import numpy as np
import panel as pn


dates = np.arange('2024-01-13T20:30:00', '2024-01-14T20:31:00', dtype='datetime64[s]')
altitudes = np.arange(0, len(dates))

mypoints = hv.Points((dates, altitudes))
mypolys = hv.Polygons([[(dates[3], 0), (dates[0], 30), (dates[40], 1), (dates[40], 30)]])

ax = mypoints * mypolys

pn.Column(ax).servable()

```

However, converting the dates array to floats before creating Polygons (by adding a `dates = dates.astype(float)` between the definitions of mypoints and my polys results in a `TypeError: The DType <class 'numpy.dtype[datetime64]'> could not be promoted by <class 'numpy.dtype[float64]'>. This means that no common DType exists for the given inputs. For example they cannot be stored in a single array unless the dtype is `object`. The full list of DTypes is: (<class 'numpy.dtype[datetime64]'>, <class 'numpy.dtype[float64]'>)`

Full tracebacks:

<details>
<summary>Using datetime64 in polygon</summary>

```pytb

2024-01-13 14:33:46,989 Starting Bokeh server version 3.2.2 (running on Tornado 6.3.3)
2024-01-13 14:33:46,990 User authentication hooks NOT provided (default user enabled)
2024-01-13 14:33:46,992 Bokeh app running at: http://localhost:5006/polydatetime
2024-01-13 14:33:46,992 Starting Bokeh server with process id: 84202
2024-01-13 14:33:57,282 404 GET /polydates (100.82.33.144) 1.34ms
2024-01-13 14:34:06,052 Error running application handler <bokeh.application.handlers.script.ScriptHandler object at 0x14067a650>: float() argument must be a string or a real number, not 'datetime.datetime'
File 'multipath.py', line 569, in ensure_ring:
breaks = np.where(np.isnan(geom.astype('float')).sum(axis=1))[0] Traceback (most recent call last):
  File "/Users/stgardner4/micromamba/envs/interactive-pyxlmadev/lib/python3.11/site-packages/bokeh/application/handlers/code_runner.py", line 229, in run
    exec(self._code, module.__dict__)
  File "/Users/stgardner4/Desktop/pyxlma-interactive/polydatetime.py", line 14, in <module>
    pn.Column(ax).servable()
  File "/Users/stgardner4/micromamba/envs/interactive-pyxlmadev/lib/python3.11/site-packages/panel/viewable.py", line 392, in servable
    self.server_doc(title=title, location=location) # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/stgardner4/micromamba/envs/interactive-pyxlmadev/lib/python3.11/site-packages/panel/viewable.py", line 1024, in server_doc
    model = self.get_root(doc)
            ^^^^^^^^^^^^^^^^^^
  File "/Users/stgardner4/micromamba/envs/interactive-pyxlmadev/lib/python3.11/site-packages/panel/layout/base.py", line 306, in get_root
    root = super().get_root(doc, comm, preprocess)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/stgardner4/micromamba/envs/interactive-pyxlmadev/lib/python3.11/site-packages/panel/viewable.py", line 666, in get_root
    root = self._get_model(doc, comm=comm)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/stgardner4/micromamba/envs/interactive-pyxlmadev/lib/python3.11/site-packages/panel/layout/base.py", line 174, in _get_model
    objects, _ = self._get_objects(model, [], doc, root, comm)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/stgardner4/micromamba/envs/interactive-pyxlmadev/lib/python3.11/site-packages/panel/layout/base.py", line 156, in _get_objects
    child = pane._get_model(doc, root, model, comm)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/stgardner4/micromamba/envs/interactive-pyxlmadev/lib/python3.11/site-packages/panel/pane/holoviews.py", line 411, in _get_model
    plot = self._render(doc, comm, root)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/stgardner4/micromamba/envs/interactive-pyxlmadev/lib/python3.11/site-packages/panel/pane/holoviews.py", line 506, in _render
    return renderer.get_plot(self.object, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/stgardner4/micromamba/envs/interactive-pyxlmadev/lib/python3.11/site-packages/holoviews/plotting/bokeh/renderer.py", line 68, in get_plot
    plot = super().get_plot(obj, doc, renderer, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/stgardner4/micromamba/envs/interactive-pyxlmadev/lib/python3.11/site-packages/holoviews/plotting/renderer.py", line 240, in get_plot
    plot.update(init_key)
  File "/Users/stgardner4/micromamba/envs/interactive-pyxlmadev/lib/python3.11/site-packages/holoviews/plotting/plot.py", line 955, in update
    return self.initialize_plot()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/stgardner4/micromamba/envs/interactive-pyxlmadev/lib/python3.11/site-packages/holoviews/plotting/bokeh/element.py", line 2897, in initialize_plot
    child = subplot.initialize_plot(ranges, plot, plots)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/stgardner4/micromamba/envs/interactive-pyxlmadev/lib/python3.11/site-packages/holoviews/plotting/bokeh/element.py", line 1885, in initialize_plot
    self._init_glyphs(plot, element, ranges, source)
  File "/Users/stgardner4/micromamba/envs/interactive-pyxlmadev/lib/python3.11/site-packages/holoviews/plotting/bokeh/element.py", line 1804, in _init_glyphs
    data, mapping, style = self.get_data(element, ranges, style)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/stgardner4/micromamba/envs/interactive-pyxlmadev/lib/python3.11/site-packages/holoviews/plotting/bokeh/path.py", line 245, in get_data
    xs, ys = multi_polygons_data(element)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/stgardner4/micromamba/envs/interactive-pyxlmadev/lib/python3.11/site-packages/holoviews/plotting/bokeh/util.py", line 1023, in multi_polygons_data
    xs, ys = (element.dimension_values(kd, expanded=False) for kd in element.kdims)
    ^^^^^^
  File "/Users/stgardner4/micromamba/envs/interactive-pyxlmadev/lib/python3.11/site-packages/holoviews/plotting/bokeh/util.py", line 1023, in <genexpr>
    xs, ys = (element.dimension_values(kd, expanded=False) for kd in element.kdims)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/stgardner4/micromamba/envs/interactive-pyxlmadev/lib/python3.11/site-packages/holoviews/core/data/__init__.py", line 196, in pipelined_fn
    result = method_fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/stgardner4/micromamba/envs/interactive-pyxlmadev/lib/python3.11/site-packages/holoviews/core/data/__init__.py", line 1099, in dimension_values
    values = self.interface.values(self, dim, expanded, flat)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/stgardner4/micromamba/envs/interactive-pyxlmadev/lib/python3.11/site-packages/holoviews/core/data/multipath.py", line 418, in values
    dvals = ensure_ring(gvals, dvals)
            ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/stgardner4/micromamba/envs/interactive-pyxlmadev/lib/python3.11/site-packages/holoviews/core/data/multipath.py", line 569, in ensure_ring
    breaks = np.where(np.isnan(geom.astype('float')).sum(axis=1))[0]
                               ^^^^^^^^^^^^^^^^^^^^
TypeError: float() argument must be a string or a real number, not 'datetime.datetime'

```
</details>

<details>
<summary>Using float64 in polygon</summary>

```pytb
2024-01-13 14:37:28,720 Error running application handler <bokeh.application.handlers.script.ScriptHandler object at 0x12f322f90>: The DType <class 'numpy.dtype[datetime64]'> could not be promoted by <class 'numpy.dtype[float64]'>. This means that no common DType exists for the given inputs. For example they cannot be stored in a single array unless the dtype is `object`. The full list of DTypes is: (<class 'numpy.dtype[datetime64]'>, <class 'numpy.dtype[float64]'>)
File 'fromnumeric.py', line 86, in _wrapreduction:
return ufunc.reduce(obj, axis, dtype, out, **passkwargs) Traceback (most recent call last):
  File "/Users/stgardner4/micromamba/envs/interactive-pyxlmadev/lib/python3.11/site-packages/holoviews/plotting/bokeh/element.py", line 478, in _axis_props
    l, b, r, t = self.get_extents(range_el, ranges, dimension=dim)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/stgardner4/micromamba/envs/interactive-pyxlmadev/lib/python3.11/site-packages/holoviews/plotting/plot.py", line 1988, in get_extents
    extents = {k: util.max_extents(rs, zrange) for k, rs in subplot_extents.items()}
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/stgardner4/micromamba/envs/interactive-pyxlmadev/lib/python3.11/site-packages/holoviews/plotting/plot.py", line 1988, in <dictcomp>
    extents = {k: util.max_extents(rs, zrange) for k, rs in subplot_extents.items()}
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/stgardner4/micromamba/envs/interactive-pyxlmadev/lib/python3.11/site-packages/holoviews/core/util.py", line 1123, in max_extents
    extents[lidx] = np.min(lower)
                    ^^^^^^^^^^^^^
  File "<__array_function__ internals>", line 200, in amin
  File "/Users/stgardner4/micromamba/envs/interactive-pyxlmadev/lib/python3.11/site-packages/numpy/core/fromnumeric.py", line 2946, in amin
    return _wrapreduction(a, np.minimum, 'min', axis, None, out,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/stgardner4/micromamba/envs/interactive-pyxlmadev/lib/python3.11/site-packages/numpy/core/fromnumeric.py", line 86, in _wrapreduction
    return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: The DType <class 'numpy.dtype[datetime64]'> could not be promoted by <class 'numpy.dtype[float64]'>. This means that no common DType exists for the given inputs. For example they cannot be stored in a single array unless the dtype is `object`. The full list of DTypes is: (<class 'numpy.dtype[datetime64]'>, <class 'numpy.dtype[float64]'>)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/stgardner4/micromamba/envs/interactive-pyxlmadev/lib/python3.11/site-packages/bokeh/application/handlers/code_runner.py", line 229, in run
    exec(self._code, module.__dict__)
  File "/Users/stgardner4/Desktop/pyxlma-interactive/polydatetime.py", line 15, in <module>
    pn.Column(ax).servable()
  File "/Users/stgardner4/micromamba/envs/interactive-pyxlmadev/lib/python3.11/site-packages/panel/viewable.py", line 392, in servable
    self.server_doc(title=title, location=location) # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/stgardner4/micromamba/envs/interactive-pyxlmadev/lib/python3.11/site-packages/panel/viewable.py", line 1024, in server_doc
    model = self.get_root(doc)
            ^^^^^^^^^^^^^^^^^^
  File "/Users/stgardner4/micromamba/envs/interactive-pyxlmadev/lib/python3.11/site-packages/panel/layout/base.py", line 306, in get_root
    root = super().get_root(doc, comm, preprocess)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/stgardner4/micromamba/envs/interactive-pyxlmadev/lib/python3.11/site-packages/panel/viewable.py", line 666, in get_root
    root = self._get_model(doc, comm=comm)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/stgardner4/micromamba/envs/interactive-pyxlmadev/lib/python3.11/site-packages/panel/layout/base.py", line 174, in _get_model
    objects, _ = self._get_objects(model, [], doc, root, comm)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/stgardner4/micromamba/envs/interactive-pyxlmadev/lib/python3.11/site-packages/panel/layout/base.py", line 156, in _get_objects
    child = pane._get_model(doc, root, model, comm)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/stgardner4/micromamba/envs/interactive-pyxlmadev/lib/python3.11/site-packages/panel/pane/holoviews.py", line 411, in _get_model
    plot = self._render(doc, comm, root)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/stgardner4/micromamba/envs/interactive-pyxlmadev/lib/python3.11/site-packages/panel/pane/holoviews.py", line 506, in _render
    return renderer.get_plot(self.object, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/stgardner4/micromamba/envs/interactive-pyxlmadev/lib/python3.11/site-packages/holoviews/plotting/bokeh/renderer.py", line 68, in get_plot
    plot = super().get_plot(obj, doc, renderer, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/stgardner4/micromamba/envs/interactive-pyxlmadev/lib/python3.11/site-packages/holoviews/plotting/renderer.py", line 240, in get_plot
    plot.update(init_key)
  File "/Users/stgardner4/micromamba/envs/interactive-pyxlmadev/lib/python3.11/site-packages/holoviews/plotting/plot.py", line 955, in update
    return self.initialize_plot()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/stgardner4/micromamba/envs/interactive-pyxlmadev/lib/python3.11/site-packages/holoviews/plotting/bokeh/element.py", line 2884, in initialize_plot
    plot = self._init_plot(key, element, ranges=ranges, plots=plots)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/stgardner4/micromamba/envs/interactive-pyxlmadev/lib/python3.11/site-packages/holoviews/plotting/bokeh/element.py", line 645, in _init_plot
    axis_specs['x']['x'] = self._axis_props(plots, subplots, element, ranges, pos=0) + (self.xaxis, {})
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/stgardner4/micromamba/envs/interactive-pyxlmadev/lib/python3.11/site-packages/holoviews/plotting/bokeh/element.py", line 482, in _axis_props
    l, b, r, t = self.get_extents(range_el, ranges)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/stgardner4/micromamba/envs/interactive-pyxlmadev/lib/python3.11/site-packages/holoviews/plotting/plot.py", line 1988, in get_extents
    extents = {k: util.max_extents(rs, zrange) for k, rs in subplot_extents.items()}
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/stgardner4/micromamba/envs/interactive-pyxlmadev/lib/python3.11/site-packages/holoviews/plotting/plot.py", line 1988, in <dictcomp>
    extents = {k: util.max_extents(rs, zrange) for k, rs in subplot_extents.items()}
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/stgardner4/micromamba/envs/interactive-pyxlmadev/lib/python3.11/site-packages/holoviews/core/util.py", line 1123, in max_extents
    extents[lidx] = np.min(lower)
                    ^^^^^^^^^^^^^
  File "<__array_function__ internals>", line 200, in amin
  File "/Users/stgardner4/micromamba/envs/interactive-pyxlmadev/lib/python3.11/site-packages/numpy/core/fromnumeric.py", line 2946, in amin
    return _wrapreduction(a, np.minimum, 'min', axis, None, out,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/stgardner4/micromamba/envs/interactive-pyxlmadev/lib/python3.11/site-packages/numpy/core/fromnumeric.py", line 86, in _wrapreduction
    return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: The DType <class 'numpy.dtype[datetime64]'> could not be promoted by <class 'numpy.dtype[float64]'>. This means that no common DType exists for the given inputs. For example they cannot be stored in a single array unless the dtype is `object`. The full list of DTypes is: (<class 'numpy.dtype[datetime64]'>, <class 'numpy.dtype[float64]'>)
```
</details>

- [x] I may be interested in making a pull request to address this 
...but I'm going to need some assistance as to where to begin debugging

**Comment by ahuang11** [comment]
Hi thanks for reporting!

I don't fully understand this; specifically I can't wrap my head around why Polygons would have a datetime x. Can you share your use case?

**Comment by wx4stg** [comment]
I have some data of the altitudes of lightning points at different times, and the idea is to allow the user of a Panel application to draw polygons around the points and click panel widget buttons to interact with them in various ways (for research/analysis). I would use the PolySelect tool, but I want to be able to allow multiple polygon selections on screen simultaneously, and I don't want the action to be taken as soon as the selection is finished, I want the selection to "stay there" while the user decides what to do with the points they just enclosed.

I was able to work around this by using the PolyDraw tool that was being passed to a DynamicMap stream input, but the problem there is that I have multiple streams with an output of `data`, and so I was using `.rename` to change the output name, but this cased another issue (#6065)...

So then I thought "well maybe I should just make the polygons have an alpha of 0, and overlay my own polygons that get programatically generated, so that the user has no idea anything is going on". This is how I discovered that polygons can't be plotted on a datetime axis. This is of course janky and bad, but that's my use case... but luckily...

I was able to work around this issue by adding a subscriber instead of using a DynamicMap with a stream input, but since I came across the inability to plot polys on a datetime axis in the intermediary, I figured I might as well document that it's a problem (in case someone else wants this).

So, to answer your question, my use case was a bad workaround that I no longer need. but maybe someone else might.
