### ISSUE TITLE
'color_key' argument ignored in datashade

### ISSUE THREAD

**Issue by rfenouil** [holoviz/holoviews#6095]
Hello, thank you for the great ecosystem you are building.
I'm trying to reproduce some Datashader examples and have trouble using the `color_key` parameter. It seems to be ignored and replaced internally by a default value (Set1 ?) in my attempts.

I first experienced the problem with [NYC Taxi dashboard example](https://examples.holoviz.org/nyc_taxi/nyc_taxi.html), then on my own datasets.
I can replicate in a minimal example below.

I'm not sure if it is really a bug, related to my environment, or a misuse of the library.
Any guidance on this matter would be appreciated.

Thank you for your help !

#### ALL software version info

```python
datashader==0.16.0
numpy==1.24.4
holoviews==1.18.1
pandas==1.5.3
dask==2023.11.0
cudf==23.12.01
dask_cudf==23.12.01
cupy==12.3.0
panel==1.3.6
param==2.0.1
colorcet==3.0.1
bokeh==3.3.2
```

#### Description of expected behavior and the observed behavior

When using `datashade` with an aggregator `by("my_categories", ds.count())`, it seems that  `color_key` is ignored when provided.
I would expect my points to be colored according to the provided colors in `color_key` (tried with list or dict) but it seems that it uses `Set1` instead.

Interestingly, the plot legend does take the specified colors as expected, but not the actual points.

Additional clue : whatever the color scale specified (even colorcet with 256 colors), I cannot use more than 22 categories otherwise I get the error message:
```
ValueError('Insufficient colors provided (22) for the categorical fields available (24)')
```

First experienced that with the 24 hour coloring in [NYC Taxi dashboard example](https://examples.holoviz.org/nyc_taxi/nyc_taxi.html).
That's why I suspect the `color_key` parameter is actually replaced internally with a 22 colors one.

#### Complete, minimal, self-contained example code that reproduces the issue

Based on [datashader documentation example](https://holoviews.org/user_guide/Large_Data.html#multidimensional-plots), here is a code example showing the problem:
```python
import holoviews as hv
import datashader as ds
from holoviews.operation.datashader import datashade, rasterize, shade, dynspread, spread
import numpy as np
import pandas as pd

hv.extension('bokeh','matplotlib', width=100)

### Helper functions to create points dataset
# from: https://holoviews.org/user_guide/Large_Data.html#multidimensional-plots
np.random.seed(3)

def random_cov():
    """Random covariance for use in generating 2D Gaussian distributions"""
    A = np.random.randn(2,2)
    return np.dot(A, A.T)

def rand_gauss2d(value=0, n=100000):
    """Return a randomly shaped 2D Gaussian distribution with an associated numeric value"""
    g = 100*np.random.multivariate_normal(np.random.randn(2), random_cov(), (n,))
    return np.hstack((g,value*np.ones((g.shape[0],1))))

    
### Table of colors (as in NYC taxi dashboard example: https://examples.holoviz.org/nyc_taxi/nyc_taxi.html)
colors = ["#FF0000","#FF3F00","#FF7F00","#FFBF00","#FFFF00","#BFFF00","#7FFF00","#3FFF00",
          "#00FF00","#00FF3F","#00FF7F","#00FFBF","#00FFFF","#00BFFF","#007FFF","#003FFF",
          "#0000FF","#3F00FF","#7F00FF","#BF00FF","#FF00FF","#FF00BF","#FF007F","#FF003F"]


### Generate a global dataset (5 gaussians with different values)
dataset = pd.concat([pd.DataFrame(rand_gauss2d(i), columns = ["x","y","k"]) for i in range(5)])
dataset["k"] = dataset["k"].astype(str) # Convert the category to string (just to be sure)

### Create HV data representations
# No "color_key" specified
no_color_key = dynspread(datashade(hv.Points(dataset),
                                   aggregator=ds.by("k",ds.count()))
                        ).opts(title="no_color_key")

# "color_key" specified as list
color_key_list = dynspread(datashade(hv.Points(dataset), 
                                     aggregator=ds.by('k', ds.count()),
                                     color_key=colors)
                          ).opts(title="color_key_list")

# "color_key" specified as dict
color_key_dict = dynspread(datashade(hv.Points(dataset), 
                                     aggregator=ds.by('k', ds.count()),
                                     color_key={str(k):col for k,col in zip(dataset["k"].unique(), colors)}) # Create a dict based on 'k' names and first colors in list
                          ).opts(title="color_key_dict")

# "color_key" specified as arbitrary value
color_key_arbitrary = dynspread(datashade(hv.Points(dataset), 
                                          aggregator=ds.by('k', ds.count()),
                                          color_key="dummy_value")
                               ).opts(title="color_key_arbitrary")


### Render all
(no_color_key + color_key_list + color_key_dict + color_key_arbitrary).opts(width=600)

```

#### Screenshots or screencasts of the bug in action

![bokeh_plot(3)](https://github.com/holoviz/datashader/assets/35697321/978067f5-83d0-4086-aa56-477933a7cdc0)

**Comment by jbednar** [comment]
Thanks for the nicely reproducible code! I've moved this to the holoviews repository, since you're using HoloViews here and from what I can see the issue is in how HoloViews is calling Datashader rather than Datashader itself.

I can reproduce the output you have above, and how I would summarize it is that the color_key is being respected for creating the legend, but somehow not being passed to Datashader for the colormapping. Maybe some of the work we did recently for supporting colormapping being done directly in Bokeh has interfered with the passing of this option down to Datashader? Definitely seems like something we need to fix.

In the meantime, because of that work, you should be able to use `rasterize` instead:

```python
colors = ["purple","pink","orange","springgreen","gray"]
color_key_list = rasterize(hv.Points(dataset), aggregator=ds.by('k', ds.count())).opts(cmap=colors, title="color_key_list")
```

<img width="253" alt="image" src="https://github.com/holoviz/holoviews/assets/1695496/1ea1f0be-a4ba-4f82-9bfe-66c61d97f6d1">

That said, using `rasterize` here is really causing my browser to have hiccups, with the correct output generated but being unresponsive for many tens of seconds.  I'll open another issue about that, but in the meantime, this issue also needs fixing!

**Comment by Hoxbro** [comment]
Can you try out the new release of HoloViews 1.18.2? This is the output I get with it (color_key_arbitrary will also now fail)

![image](https://github.com/holoviz/holoviews/assets/19758978/0324510a-54bc-48e4-8f68-478f81461026)

I haven't looked into in detail, but the fix could have been in https://github.com/holoviz/holoviews/pull/5994

**Comment by jbednar** [comment]
That fixes it, thanks! And thanks for releasing 1.18.2 with the fix so quickly.

**Comment by rfenouil** [comment]
Hi, thank you so much for this ! Color problem solved indeed ! :)

However (sorry)... In my environment the Datashading does not work anymore -> When I zoom in the figure I don't get any update of the data, it stays at 'low res' (ie. I get the zoomed square).

![Screenshot from 2024-02-06 17-05-34](https://github.com/holoviz/holoviews/assets/35697321/e86a3f2b-969d-45d3-85a6-9b9370354b98)

Is it functional on your side ?

**Comment by Hoxbro** [comment]
It is: 


https://github.com/holoviz/holoviews/assets/19758978/da1e58e8-8b63-4f26-8778-e4abbbb7fc93

Is there any message in the console log?

**Comment by rfenouil** [comment]
Actually yes:

```
[I 2024-02-06 17:49:22.605 ServerApp] Kernel started: 93407a6f-76f1-4de7-8ef1-ce21234c6cdd
2024-02-06 17:49:29,907 ERROR: panel.io.jupyter_server_extension - Task exception was never retrieved             
future: <Task finished name='Task-13' coro=<Callback.process_on_change() done, defined at /opt/conda/lib/python3.10/site-packages/holoviews/plotting/bokeh/cal
lbacks.py:356> exception=AbbreviatedException(<class 'RuntimeError'>, RuntimeError('_pending_writes should be non-None when we have a document lock, and we sh
ould have the lock when the document changes'), <traceback object at 0x7fd455435140>)>
Traceback (most recent call last):                                                                                                                              File "/opt/conda/lib/python3.10/site-packages/holoviews/plotting/bokeh/element.py", line 1954, in _update_glyphs
    self._update_glyph(renderer, properties, mapping, glyph, source, data)
  File "/opt/conda/lib/python3.10/site-packages/holoviews/plotting/bokeh/element.py", line 1737, in _update_glyph
    self._update_datasource(source, data)
  File "/opt/conda/lib/python3.10/site-packages/holoviews/plotting/bokeh/plot.py", line 192, in _update_datasource                                                source.data.update(data)                                                                                                                                    File "/opt/conda/lib/python3.10/site-packages/bokeh/core/property/wrappers.py", line 433, in update
    descriptor._notify_mutated(owner, old, hint=hint)
  File "/opt/conda/lib/python3.10/site-packages/bokeh/core/property/descriptors.py", line 658, in _notify_mutated
    self._set(obj, old, value, hint=hint)
  File "/opt/conda/lib/python3.10/site-packages/bokeh/core/property/descriptors.py", line 621, in _set
    self._trigger(obj, old, value, hint=hint, setter=setter)
  File "/opt/conda/lib/python3.10/site-packages/bokeh/core/property/descriptors.py", line 699, in _trigger
    obj.trigger(self.name, old, value, hint, setter)
  File "/opt/conda/lib/python3.10/site-packages/bokeh/model/model.py", line 569, in trigger
    super().trigger(descriptor.name, old, new, hint=hint, setter=setter)
  File "/opt/conda/lib/python3.10/site-packages/bokeh/util/callback_manager.py", line 188, in trigger
    self.document.callbacks.notify_change(cast(Model, self), attr, old, new, hint, setter, invoke)
  File "/opt/conda/lib/python3.10/site-packages/bokeh/document/callbacks.py", line 249, in notify_change
    self.trigger_on_change(event)
  File "/opt/conda/lib/python3.10/site-packages/bokeh/document/callbacks.py", line 413, in trigger_on_change
    invoke_with_curdoc(doc, invoke_callbacks)
  File "/opt/conda/lib/python3.10/site-packages/bokeh/document/callbacks.py", line 443, in invoke_with_curdoc
    return f()
  File "/opt/conda/lib/python3.10/site-packages/bokeh/document/callbacks.py", line 412, in invoke_callbacks
    cb(event)
  File "/opt/conda/lib/python3.10/site-packages/bokeh/document/callbacks.py", line 276, in <lambda>
    self._change_callbacks[receiver] = lambda event: event.dispatch(receiver)
  File "/opt/conda/lib/python3.10/site-packages/bokeh/document/events.py", line 427, in dispatch
    super().dispatch(receiver)
  File "/opt/conda/lib/python3.10/site-packages/bokeh/document/events.py", line 219, in dispatch
    cast(DocumentPatchedMixin, receiver)._document_patched(self)
  File "/opt/conda/lib/python3.10/site-packages/bokeh/server/session.py", line 244, in _document_patched
    raise RuntimeError("_pending_writes should be non-None when we have a document lock, and we should have the lock when the document changes")
RuntimeError: _pending_writes should be non-None when we have a document lock, and we should have the lock when the document changes

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/site-packages/holoviews/plotting/bokeh/callbacks.py", line 388, in process_on_change
    self.on_msg(msg)
  File "/opt/conda/lib/python3.10/site-packages/holoviews/plotting/bokeh/callbacks.py", line 221, in on_msg
    raise e
  File "/opt/conda/lib/python3.10/site-packages/holoviews/plotting/bokeh/callbacks.py", line 213, in on_msg
    Stream.trigger(streams)
  File "/opt/conda/lib/python3.10/site-packages/holoviews/streams.py", line 189, in trigger
    subscriber(**dict(union))
  File "/opt/conda/lib/python3.10/site-packages/holoviews/plotting/plot.py", line 243, in refresh
    raise e
  File "/opt/conda/lib/python3.10/site-packages/holoviews/plotting/plot.py", line 239, in refresh
    self._trigger_refresh(stream_key)
  File "/opt/conda/lib/python3.10/site-packages/holoviews/plotting/plot.py", line 257, in _trigger_refresh
    self.update(key)
  File "/opt/conda/lib/python3.10/site-packages/holoviews/plotting/plot.py", line 956, in update
    item = self.__getitem__(key)
  File "/opt/conda/lib/python3.10/site-packages/holoviews/plotting/plot.py", line 443, in __getitem__
    self.update_frame(frame)
  File "/opt/conda/lib/python3.10/site-packages/holoviews/plotting/bokeh/element.py", line 2034, in update_frame
    self._update_glyphs(element, ranges, self.style[self.cyclic_index])
  File "/opt/conda/lib/python3.10/site-packages/holoviews/plotting/bokeh/element.py", line 1953, in _update_glyphs
    with abbreviated_exception():
  File "/opt/conda/lib/python3.10/site-packages/holoviews/core/options.py", line 222, in __exit__
    raise AbbreviatedException(etype, value, traceback)
holoviews.core.options.AbbreviatedException: RuntimeError: _pending_writes should be non-None when we have a document lock, and we should have the lock when t
he document changes

To view the original traceback, catch this exception and call print_traceback() method.

```

**Comment by Hoxbro** [comment]
Can you paste the output of `hv.show_versions`?

**Comment by rfenouil** [comment]
It seems that it actually works inside the jupyter cells, and when serving the Panel from ipynb file with command line `panel serve`.
I still cannot get it to work from jupyter when clicking on the blue button 'Preview with Panel'. Could that make some sense ?

I can do some more testing and report tomorrow.
Thank you for your help.

Here is the result of `hv.show_versions()`:
```
Python              :  3.10.11 | packaged by conda-forge | (main, May 10 2023, 18:58:44) [GCC 11.3.0]
Operating system    :  Linux-6.2.0-39-generic-x86_64-with-glibc2.35
Panel comms         :  default

holoviews           :  1.18.2

bokeh               :  3.3.4
colorcet            :  3.0.1
cudf                :  23.12.1
dask                :  2023.11.0
datashader          :  0.16.0
geoviews            :  -
hvplot              :  -
ibis-framework      :  -
IPython             :  8.20.0
jupyter_bokeh       :  -
jupyterlab          :  4.0.1
matplotlib          :  3.8.0
networkx            :  3.2.1
notebook            :  6.5.4
numba               :  0.57.1
numpy               :  1.23.4
pandas              :  1.5.3
panel               :  1.3.8
param               :  2.0.2
pillow              :  10.0.1
plotly              :  5.18.0
pyarrow             :  14.0.2
pyviz_comms         :  3.0.0
scikit-image        :  0.20.0
scipy               :  1.12.0
spatialpandas       :  0.4.10
streamz             :  0.6.4
tsdownsample        :  -
xarray              :  2023.12.0
```

**Comment by Hoxbro** [comment]
> Could that make some sense ?

I just tested it and could recreate it. Can you open a new issue with a small example and description?

**Comment by rfenouil** [comment]
Sure, will do tomorrow.
Thank you !
