### ISSUE TITLE
Cannot use Dataset to hv.Polygons with grouping, custom colors, and legend

### ISSUE THREAD

**Issue by Lnk2past** [holoviz/holoviews#6379]
#### ALL software version info
(this library, plus any other relevant software, e.g. bokeh, python, notebook, OS, browser, etc should be added within the dropdown below.)

<details>
    <summary>Software Version Info</summary>

```plaintext
  python                            3.11.9
  bokeh                             3.3.4
  holoviews                         1.19.1
  notebook                          7.2.2
  
  Debian Bullseye
  Chrome Version 128.0.6613.139 (Official Build) (64-bit)
```    
</details>

#### Description of expected behavior and the observed behavior

Opening this in response to https://discourse.holoviz.org/t/dataset-to-polygons-with-groupby-legend/8183. It is not clear to me if this is all one bug, or a collection of bugs due to this happening in different ways with different setups.

When attempting to build an overlay of polygons from a dataset using a groupby, coloring 
 the polygons by some category, and showing the legend, I am met with:

```plaintext
ValueError: Only one of legend, legend_label, legend_field or legend_group may be provided, got: legend_label or legend_field
```

I would expect to see an overlay of polygons, colored by their category, with the legend showing the category colors. If I remove the categorical coloring, or the legend, the polygons are overlayed correctly (but I would be missing either the coloring or the legend).

If I pad my data to "close" the polygons and use `hv.Path` instead, the correct plot and coloring is done and a legend is provided, but the legend is incorrect (missing + incorrect entries).

If I manually construct the overlay using a loop to produce the individual `hv.Polygon` elements while also using a colormap, the correct overlay is produced, but the legend is incorrect (missing + incorrect entries).

If I manually construct the overlay using a loop to produce the individual `hv.Path` elements, then everything works (but this is way clunkier).

#### Complete, minimal, self-contained example code that reproduces the issue

```python
# code goes here between backticks
import holoviews as hv
import pandas as pd

hv.extension('bokeh')

df = pd.DataFrame({
    'x': [0, 1, 1, 1, 2, 2, 2, 3, 3],
    'y': [0, 0, 1, 0, 0, 1, 0, 0, 1],
    'id':['foo', 'foo', 'foo', 'bar', 'bar', 'bar', 'baz', 'baz', 'baz'],
    'type':['a', 'a', 'a', 'b', 'b', 'b', 'a', 'a', 'a']
})
hv.Dataset(df, kdims=['x', 'y']).to(hv.Polygons, groupby='id').overlay().opts(
    hv.opts.Polygons(color='type', cmap={'a':'red', 'b':'blue'}, show_legend=True)
)

# hv.ipython.show_traceback() # if in notebook
```

#### Stack traceback and/or browser JavaScript console output

```
Traceback (most recent call last):

  File "/root/micromamba/envs/starling/lib/python3.11/site-packages/holoviews/plotting/bokeh/element.py", line 2047, in _init_glyphs
    renderer, glyph = self._init_glyph(plot, mapping, properties)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/root/micromamba/envs/starling/lib/python3.11/site-packages/holoviews/plotting/bokeh/path.py", line 294, in _init_glyph
    renderer = getattr(plot, plot_method)(**data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/root/micromamba/envs/starling/lib/python3.11/site-packages/bokeh/plotting/_decorators.py", line 87, in wrapped
    return create_renderer(glyphclass, self.plot, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/root/micromamba/envs/starling/lib/python3.11/site-packages/bokeh/plotting/_renderer.py", line 81, in create_renderer
    legend_kwarg = pop_legend_kwarg(kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^

  File "/root/micromamba/envs/starling/lib/python3.11/site-packages/bokeh/plotting/_legends.py", line 50, in pop_legend_kwarg
    raise ValueError(f"Only one of {nice_join(LEGEND_ARGS)} may be provided, got: {nice_join(result.keys())}")

ValueError: Only one of legend, legend_label, legend_field or legend_group may be provided, got: legend_label or legend_field
```

#### Screenshots or screencasts of the bug in action

<details>

<summary>Errors and Attempted Workarounds</summary>

##### Error

![image](https://github.com/user-attachments/assets/519c2412-7f46-4fb3-88b5-4f1d6e9bbe47)

##### `hv.Path` with Incorrect Legend

![image](https://github.com/user-attachments/assets/54886ffe-ec3e-4ab7-a2b2-9f849b12f846)

##### Manual Overlay of `hv.Polygon` with incorrect legend

![image](https://github.com/user-attachments/assets/20bf20bf-f4dd-4837-9294-a3ba3f2952ad)

##### Manual (and Correct!) Overlay with `hv.Path`

![image](https://github.com/user-attachments/assets/31f32bf4-6c35-4118-a1d0-3a5b265e78d9)

Note that I am manually setting labels and colors; trying to use a column to set values results in issues.

</details>

- [ ] I may be interested in making a pull request to address this

**Comment by philippjfr** [comment]
This issue has been mentioned on **HoloViz Discourse**. There might be relevant details there:

https://discourse.holoviz.org/t/dataset-to-polygons-with-groupby-legend/8183/4
