### ISSUE TITLE
Error when importing holoviews

### ISSUE THREAD

**Issue by ivan-marroquin** [holoviz/holoviews#6400]
#### ALL software version info
holoviews 1.19.1
Ubuntu 22.04
Visual Studio Code 1.93.1
notebook 6.4.12

<details>
Open a notebook in VSC and type the command lines below:
import numpy as np
import pandas as pd
import holoviews as hv

Run the cell, and an error is reported (see below). Thanks for your help
</details>

#### Description of expected behavior and the observed behavior
No error should be reported when importing the holoviews library

#### Complete, minimal, self-contained example code that reproduces the issue

```python
# code goes here between backticks
import numpy as np
import pandas as pd
import holoviews as hv

```

#### Stack traceback and/or browser JavaScript console output
ValueError                                Traceback (most recent call last)
Cell In [11], [line 4](vscode-notebook-cell:?execution_count=11&line=4)
      [1](vscode-notebook-cell:?execution_count=11&line=1) import numpy as np
      [2](vscode-notebook-cell:?execution_count=11&line=2) import pandas as pd
----> [4](vscode-notebook-cell:?execution_count=11&line=4) import holoviews as hv

File ~/python_3.9.0/lib/python3.9/site-packages/holoviews/__init__.py:123
    [119](https://file+.vscode-resource.vscode-cdn.net/home/ivan/python_fun/Anomaly_Detection/~/python_3.9.0/lib/python3.9/site-packages/holoviews/__init__.py:119) warnings.filterwarnings("ignore",
    [120](https://file+.vscode-resource.vscode-cdn.net/home/ivan/python_fun/Anomaly_Detection/~/python_3.9.0/lib/python3.9/site-packages/holoviews/__init__.py:120)                         message="elementwise comparison failed; returning scalar instead")
    [122](https://file+.vscode-resource.vscode-cdn.net/home/ivan/python_fun/Anomaly_Detection/~/python_3.9.0/lib/python3.9/site-packages/holoviews/__init__.py:122) if "IPython" in sys.modules:
--> [123](https://file+.vscode-resource.vscode-cdn.net/home/ivan/python_fun/Anomaly_Detection/~/python_3.9.0/lib/python3.9/site-packages/holoviews/__init__.py:123)     from .ipython import notebook_extension
    [124](https://file+.vscode-resource.vscode-cdn.net/home/ivan/python_fun/Anomaly_Detection/~/python_3.9.0/lib/python3.9/site-packages/holoviews/__init__.py:124)     extension = notebook_extension
    [125](https://file+.vscode-resource.vscode-cdn.net/home/ivan/python_fun/Anomaly_Detection/~/python_3.9.0/lib/python3.9/site-packages/holoviews/__init__.py:125) else:

File ~/python_3.9.0/lib/python3.9/site-packages/holoviews/ipython/__init__.py:15
     [13](https://file+.vscode-resource.vscode-cdn.net/home/ivan/python_fun/Anomaly_Detection/~/python_3.9.0/lib/python3.9/site-packages/holoviews/ipython/__init__.py:13) from ..core.tree import AttrTree
     [14](https://file+.vscode-resource.vscode-cdn.net/home/ivan/python_fun/Anomaly_Detection/~/python_3.9.0/lib/python3.9/site-packages/holoviews/ipython/__init__.py:14) from ..element.comparison import ComparisonTestCase
---> [15](https://file+.vscode-resource.vscode-cdn.net/home/ivan/python_fun/Anomaly_Detection/~/python_3.9.0/lib/python3.9/site-packages/holoviews/ipython/__init__.py:15) from ..plotting.renderer import Renderer
     [16](https://file+.vscode-resource.vscode-cdn.net/home/ivan/python_fun/Anomaly_Detection/~/python_3.9.0/lib/python3.9/site-packages/holoviews/ipython/__init__.py:16) from ..util import extension
     [17](https://file+.vscode-resource.vscode-cdn.net/home/ivan/python_fun/Anomaly_Detection/~/python_3.9.0/lib/python3.9/site-packages/holoviews/ipython/__init__.py:17) from .display_hooks import display, png_display, pprint_display, svg_display

File ~/python_3.9.0/lib/python3.9/site-packages/holoviews/plotting/__init__.py:12
     [10](https://file+.vscode-resource.vscode-cdn.net/home/ivan/python_fun/Anomaly_Detection/~/python_3.9.0/lib/python3.9/site-packages/holoviews/plotting/__init__.py:10) from ..element.sankey import Sankey, _layout_sankey
     [11](https://file+.vscode-resource.vscode-cdn.net/home/ivan/python_fun/Anomaly_Detection/~/python_3.9.0/lib/python3.9/site-packages/holoviews/plotting/__init__.py:11) from ..operation.stats import bivariate_kde, univariate_kde
...
--> [238](https://file+.vscode-resource.vscode-cdn.net/home/ivan/python_fun/Anomaly_Detection/~/python_3.9.0/lib/python3.9/site-packages/bokeh/core/enums.py:238)     raise ValueError(f"expected a non-empty sequence of strings, got {nice_join(values)}")
    [240](https://file+.vscode-resource.vscode-cdn.net/home/ivan/python_fun/Anomaly_Detection/~/python_3.9.0/lib/python3.9/site-packages/bokeh/core/enums.py:240) if len(values) != len(set(values)):
    [241](https://file+.vscode-resource.vscode-cdn.net/home/ivan/python_fun/Anomaly_Detection/~/python_3.9.0/lib/python3.9/site-packages/bokeh/core/enums.py:241)     raise ValueError(f"enumeration items must be unique, got {nice_join(values)}")

ValueError: expected a non-empty sequence of strings, got typing.Literal['replace', 'append', 'intersect', 'subtract', 'xor'] or toggle

#### Screenshots or screencasts of the bug in action

- [ ] I may be interested in making a pull request to address this

**Comment by hoxbro** [comment]
I can't recreate it. But the notebook version seems pretty old (over two years). 

Can you try create a new environment and see if that works?

Else run this in the environment `python -c "import holoviews; holoviews.show_versions()"

**Comment by ivan-marroquin** [comment]
Hi @hoxbro 

Thanks for your quick response. I ran the command from a console and got this output. Hope this helps!

Python              :  3.9.0 (default, Sep 13 2022, 18:58:32) 
[GCC 11.2.0]
Operating system    :  Linux-6.5.0-25-generic-x86_64-with-glibc2.35
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/ivan_phd/python_3.9.0/lib/python3.9/site-packages/holoviews/util/_versions.py", line 51, in show_versions
    _panel_comms()
  File "/home/ivan_phd/python_3.9.0/lib/python3.9/site-packages/holoviews/util/_versions.py", line 67, in _panel_comms
    import panel as pn
  File "/home/ivan_phd/python_3.9.0/lib/python3.9/site-packages/panel/__init__.py", line 50, in <module>
    from . import layout  # noqa
  File "/home/ivan_phd/python_3.9.0/lib/python3.9/site-packages/panel/layout/__init__.py", line 31, in <module>
    from .accordion import Accordion  # noqa
  File "/home/ivan_phd/python_3.9.0/lib/python3.9/site-packages/panel/layout/accordion.py", line 9, in <module>
    from bokeh.models import Column as BkColumn, CustomJS
  File "/home/ivan_phd/python_3.9.0/lib/python3.9/site-packages/bokeh/models/__init__.py", line 32, in <module>
    from ..model import Model
  File "/home/ivan_phd/python_3.9.0/lib/python3.9/site-packages/bokeh/model/__init__.py", line 24, in <module>
    from .data_model import DataModel
  File "/home/ivan_phd/python_3.9.0/lib/python3.9/site-packages/bokeh/model/data_model.py", line 25, in <module>
    from .model import Model
  File "/home/ivan_phd/python_3.9.0/lib/python3.9/site-packages/bokeh/model/model.py", line 28, in <module>
    from ..core import properties as p
  File "/home/ivan_phd/python_3.9.0/lib/python3.9/site-packages/bokeh/core/properties.py", line 307, in <module>
    from .property.aliases import CoordinateLike
  File "/home/ivan_phd/python_3.9.0/lib/python3.9/site-packages/bokeh/core/property/aliases.py", line 26, in <module>
    from .factors import Factor
  File "/home/ivan_phd/python_3.9.0/lib/python3.9/site-packages/bokeh/core/property/factors.py", line 26, in <module>
    from .container import Seq, Tuple
  File "/home/ivan_phd/python_3.9.0/lib/python3.9/site-packages/bokeh/core/property/container.py", line 43, in <module>
    from .enum import Enum
  File "/home/ivan_phd/python_3.9.0/lib/python3.9/site-packages/bokeh/core/property/enum.py", line 33, in <module>
    from .. import enums
  File "/home/ivan_phd/python_3.9.0/lib/python3.9/site-packages/bokeh/core/enums.py", line 475, in <module>
    SelectionMode = enumeration(SelectionModeType)
  File "/home/ivan_phd/python_3.9.0/lib/python3.9/site-packages/bokeh/core/enums.py", line 238, in enumeration
    raise ValueError(f"expected a non-empty sequence of strings, got {nice_join(values)}")
ValueError: expected a non-empty sequence of strings, got typing.Literal['replace', 'append', 'intersect', 'subtract', 'xor'] or toggle

**Comment by ivan-marroquin** [comment]
I generated a new environment using pip command (I do not have conda on my computer). Unfortunately, I still get the same error message

**Comment by hoxbro** [comment]
Can you paste the output of pip freeze?

**Comment by ivan-marroquin** [comment]
bleach==6.1.0
bokeh==3.4.3
certifi==2024.8.30
charset-normalizer==3.3.2
colorcet==3.1.0
contourpy==1.3.0
holoviews==1.19.1
idna==3.10
importlib-metadata==8.5.0
jinja2==3.1.4
linkify-it-py==2.0.3
Markdown==3.7
markdown-it-py==3.0.0
MarkupSafe==2.1.5
mdit-py-plugins==0.4.2
mdurl==0.1.2
numpy==2.0.2
packaging==24.1
pandas==2.2.3
panel==1.4.5
param==2.1.1
pillow==10.4.0
pyspark==3.3.1
python-dateutil==2.9.0.post0
pytz==2024.2
pyviz-comms==3.0.3
PyYAML==6.0.2
requests==2.32.3
six==1.16.0
tornado==6.4.1
tqdm==4.66.5
typing-extensions==4.12.2
tzdata==2024.2
uc-micro-py==1.0.3
urllib3==2.2.3
webencodings==0.5.1
xyzservices==2024.9.0
zipp==3.20.2

**Comment by hoxbro** [comment]
I can't recreate the problem. Have you changed the environment in the notebook?

The top right corner should match your environment. 
![image](https://github.com/user-attachments/assets/df3af201-1761-48ea-a02c-096288911b63)

**Comment by ivan-marroquin** [comment]
I checked again, and the right environment is active.

![image](https://github.com/user-attachments/assets/dc907528-55ad-4caf-a534-9e6c335fe392)

My next step is to remove the package and re-install it again. Let you know, if this works.

Thanks

**Comment by ivan-marroquin** [comment]
I reinstalled holoviews in my current environment (not the virtual environment made for this issue).

Open a linux console, and run:
python
import holoviews (no error message)
holoviews.show_versions() (got the error messages reported above)

Open another linux console, and run command
python3 -c "import holoviews; holoviews.show_versions()" (got the error message reported above)

Do I need to have Python 3.10 to successfully run this package?

**Comment by hoxbro** [comment]
I think your global environment is messed up. 

In the notebook - It should show more than Python 3.9. Can you try clicking on it and see if you can change to your virtual environment?

![image](https://github.com/user-attachments/assets/32fe8be7-47ee-4657-a6c9-4f22c5de6540)

**Comment by ivan-marroquin** [comment]
Running code from a console with the virtual environment active still gives me the same issues.

It is a strange issue. As you pointed out, my working environment may be somehow corrupted. However, I have the same problem with the virtual environment. 

I downloaded and compiled the source code for the Python I am using. Could this explain the present issue?

**Comment by hoxbro** [comment]
Maybe... But hard to say. 

I will close this issue as it is a usage question. The issue tracker is for bugs and new features.
I'm going to close this issue. Feel free to ask for help via our [forum](https://discourse.holoviz.org/).
